"""Test intake through its interface — the pure, fail-safe decision parser and the
label mapping. Like the reviewer: anything we cannot read as a confident build-ready
decision must fall back to holding for a human, never an accidental `ready`.
"""

import pytest

from agentflow.intake import (IntakeRoute, awaiting_recheck, intake_labels,
                              parse_intake, replies_since_intake)
from agentflow.runner import Complexity, Effort


def test_ready_with_all_fields_is_build_ready():
    v = parse_intake('{"route": "ready", "title": "ISF: widen the measurement window", '
                     '"complexity": "standard", "effort": "high", "body": "## Agent Brief\\n..."}')
    assert v.route is IntakeRoute.READY and v.parsed
    assert v.complexity is Complexity.STANDARD and v.effort is Effort.HIGH
    assert v.title == "ISF: widen the measurement window" and v.body.startswith("## Agent Brief")


def test_ready_missing_complexity_defaults_deep():
    # A bigger model is the safe sizing miss — never a wrong build.
    v = parse_intake('{"route": "ready", "body": "brief", "effort": "low"}')
    assert v.route is IntakeRoute.READY and v.complexity is Complexity.DEEP


def test_ready_missing_effort_defaults_medium():
    assert parse_intake('{"route": "ready", "body": "b", "complexity": "deep"}').effort is Effort.MEDIUM


def test_grill_and_mockup_routes():
    assert parse_intake('{"route": "grill", "body": "which did you mean?"}').route is IntakeRoute.GRILL
    assert parse_intake('{"route": "mockup", "body": "kickoff"}').route is IntakeRoute.MOCKUP


def test_unknown_route_holds_for_human():
    v = parse_intake('{"route": "merge-it", "body": "x"}')
    assert v.route is IntakeRoute.GRILL and v.parsed is False


def test_ready_without_a_body_holds():
    assert parse_intake('{"route": "ready", "body": "   ", "complexity": "deep"}').parsed is False


def test_non_object_payload_holds():
    v = parse_intake('["ready"]')
    assert v.route is IntakeRoute.GRILL and v.parsed is False


def test_prose_then_fenced_json_is_parsed():
    payload = 'Here you go:\n```json\n{"route": "grill", "body": "which did you mean?"}\n```\n'
    assert parse_intake(payload).route is IntakeRoute.GRILL


# fail-safe: whatever the input, intake never raises and never invents a `ready`
@pytest.mark.parametrize("payload", ["", "null", "5", "not json", '{"route": 5}',
                                     '{"route": "ready"}', '{"body": "x"}', '{"route"}'])
def test_parse_never_raises_and_holds(payload):
    assert parse_intake(payload).route is IntakeRoute.GRILL


def test_labels_for_ready_carry_both_dials():
    r = parse_intake('{"route": "ready", "body": "b", "complexity": "deep", "effort": "extra"}')
    assert intake_labels(r) == ["ready-for-agent", "agentflow:complexity:deep", "agentflow:effort:extra"]


def test_labels_for_holds_are_a_single_state():
    assert intake_labels(parse_intake('{"route": "grill", "body": "q"}')) == ["agentflow:needs-grilling"]
    assert intake_labels(parse_intake('{"route": "mockup", "body": "m"}')) == ["agentflow:needs-mockup"]


def _c(body):
    return {"body": body}


def test_awaiting_recheck_true_when_maintainer_replied_last():
    comments = [_c("> *agentflow intake — generated by AI.*\n\nwhich did you mean?"),
                _c("option a, keep it simple")]
    assert awaiting_recheck(comments) is True


def test_awaiting_recheck_false_when_intake_spoke_last():
    comments = [_c("some human note"),
                _c("> *agentflow intake — generated by AI.*\n\nsharpened question?")]
    assert awaiting_recheck(comments) is False


def test_awaiting_recheck_false_without_comments():
    assert awaiting_recheck([]) is False
    assert awaiting_recheck([_c("   ")]) is False


def test_replies_since_intake_collects_only_the_new_answer():
    comments = [_c("> *agentflow intake — generated by AI.*\n\nold questions"),
                _c("answer one"), _c("answer two")]
    assert replies_since_intake(comments) == "answer one\n\nanswer two"
