"""Test intake through its interface — the pure, fail-safe decision parser and the
label mapping. Like the reviewer: anything we cannot read as a confident build-ready
decision must fall back to holding for a human, never an accidental `ready`.
"""

import json
from types import SimpleNamespace

import pytest

from agentflow import intake as intake_mod
from agentflow.intake import (INTAKE_MARK, IntakeResult, IntakeRoute, apply_intake,
                              awaiting_recheck, compose_ready_body, intake_labels,
                              parse_intake, replies_since_intake)
from agentflow.runner import Complexity, Effort


def test_ready_with_all_fields_is_build_ready():
    v = parse_intake('{"route": "ready", "title": "ISF: widen the measurement window", '
                     '"complexity": "standard", "effort": "high", "body": "## Agent Brief\\n..."}')
    assert v.route is IntakeRoute.READY and v.parsed
    assert v.complexity is Complexity.STANDARD and v.effort is Effort.HIGH
    assert v.title == "ISF: widen the measurement window" and v.body.startswith("## Agent Brief")


def test_ready_missing_complexity_defaults_deep():
    # A bigger model is the safe sizing miss — never a wrong build.
    v = parse_intake('{"route": "ready", "body": "brief", "effort": "low"}')
    assert v.route is IntakeRoute.READY and v.complexity is Complexity.DEEP


def test_ready_missing_effort_defaults_medium():
    assert parse_intake('{"route": "ready", "body": "b", "complexity": "deep"}').effort is Effort.MEDIUM


def test_grill_and_mockup_routes():
    assert parse_intake('{"route": "grill", "body": "which did you mean?"}').route is IntakeRoute.GRILL
    assert parse_intake('{"route": "mockup", "body": "kickoff"}').route is IntakeRoute.MOCKUP


def test_unknown_route_holds_for_human():
    v = parse_intake('{"route": "merge-it", "body": "x"}')
    assert v.route is IntakeRoute.GRILL and v.parsed is False


def test_ready_without_a_body_holds():
    assert parse_intake('{"route": "ready", "body": "   ", "complexity": "deep"}').parsed is False


def test_non_object_payload_holds():
    v = parse_intake('["ready"]')
    assert v.route is IntakeRoute.GRILL and v.parsed is False


def test_prose_then_fenced_json_is_parsed():
    payload = 'Here you go:\n```json\n{"route": "grill", "body": "which did you mean?"}\n```\n'
    assert parse_intake(payload).route is IntakeRoute.GRILL


def test_prose_then_bare_json_object_is_recovered():
    # The real dry-run failure: the model reasons, then emits a bare (unfenced) JSON
    # object with \n-escaped body. parse must recover the decision, not choke on prose.
    payload = ("The premise doesn't hold - truncate already exists.\n\n"
               "It shipped in #4 with tests, so there is nothing to build.\n\n"
               '{"route": "grill", "title": "truncate: clarify the cap", '
               '"body": "> *agentflow intake*\\n\\n**Already built.** Which did you mean?"}')
    v = parse_intake(payload)
    assert v.route is IntakeRoute.GRILL and v.parsed
    assert "Already built" in v.body and v.title.startswith("truncate")


def test_prose_then_json_ready_recovers_dials():
    payload = ('Grounded against the code; a clean add.\n'
               '{"route":"ready","body":"## Brief","complexity":"deep","effort":"high"}')
    v = parse_intake(payload)
    assert v.route is IntakeRoute.READY and v.complexity is Complexity.DEEP and v.effort is Effort.HIGH


def test_last_json_object_wins_over_an_example_in_prose():
    payload = ('For example I might answer {"route": "ready", "body": "x"} but actually\n'
               '{"route": "grill", "body": "the real question"}')
    v = parse_intake(payload)
    assert v.route is IntakeRoute.GRILL and v.body == "the real question"


# fail-safe: whatever the input, intake never raises and never invents a `ready`
@pytest.mark.parametrize("payload", ["", "null", "5", "not json", '{"route": 5}',
                                     '{"route": "ready"}', '{"body": "x"}', '{"route"}'])
def test_parse_never_raises_and_holds(payload):
    assert parse_intake(payload).route is IntakeRoute.GRILL


def test_labels_for_ready_carry_both_dials():
    r = parse_intake('{"route": "ready", "body": "b", "complexity": "deep", "effort": "extra"}')
    assert intake_labels(r) == ["ready-for-agent", "agentflow:complexity:deep", "agentflow:effort:extra"]


def test_labels_for_holds_are_a_single_state():
    assert intake_labels(parse_intake('{"route": "grill", "body": "q"}')) == ["agentflow:needs-grilling"]
    assert intake_labels(parse_intake('{"route": "mockup", "body": "m"}')) == ["agentflow:needs-mockup"]


def _c(body):
    return {"body": body}


def test_awaiting_recheck_true_when_maintainer_replied_last():
    comments = [_c("> *agentflow intake — generated by AI.*\n\nwhich did you mean?"),
                _c("option a, keep it simple")]
    assert awaiting_recheck(comments) is True


def test_awaiting_recheck_false_when_intake_spoke_last():
    comments = [_c("some human note"),
                _c("> *agentflow intake — generated by AI.*\n\nsharpened question?")]
    assert awaiting_recheck(comments) is False


def test_awaiting_recheck_false_without_comments():
    assert awaiting_recheck([]) is False
    assert awaiting_recheck([_c("   ")]) is False


def test_replies_since_intake_collects_only_the_new_answer():
    comments = [_c("> *agentflow intake — generated by AI.*\n\nold questions"),
                _c("answer one"), _c("answer two")]
    assert replies_since_intake(comments) == "answer one\n\nanswer two"


# --- the brief lands in the body (issue #16) -------------------------------------

def test_compose_ready_body_puts_brief_on_top_original_below():
    body = compose_ready_body("## Agent Brief\nthe scope", "the one-line as-filed text")
    assert body.startswith("## Agent Brief")
    # the as-filed text survives, under a collapsed block below the brief
    assert "<details>" in body and "the one-line as-filed text" in body
    assert body.index("## Agent Brief") < body.index("<details>")


def test_compose_ready_body_updates_in_place_on_reintake():
    # A second intake replaces the brief but must NOT nest the old brief or add a
    # second <details> — the true original stays preserved exactly once.
    first = compose_ready_body("## Brief v1", "the one-line as-filed text")
    second = compose_ready_body("## Brief v2", first)
    assert second.startswith("## Brief v2") and "## Brief v1" not in second
    assert second.count("<details>") == 1
    assert second.count("the one-line as-filed text") == 1


class _GhRecorder:
    """Capture the gh commands apply_intake runs, and answer its body fetch."""

    def __init__(self, current_body=""):
        self.calls = []
        self.current_body = current_body

    def __call__(self, cmd, cwd=None):
        self.calls.append(cmd)
        if "issue" in cmd and "view" in cmd:
            return SimpleNamespace(returncode=0, stdout=json.dumps({"body": self.current_body}))
        return SimpleNamespace(returncode=0, stdout="")

    def _edit_body(self):
        for c in self.calls:
            if "edit" in c and "--body" in c:
                return c[c.index("--body") + 1]
        return None

    def _comment(self):
        for c in self.calls:
            if "comment" in c and "--body" in c:
                return c[c.index("--body") + 1]
        return None


def test_apply_intake_ready_writes_brief_to_body_and_a_short_comment(monkeypatch):
    rec = _GhRecorder(current_body="original one-liner as filed")
    monkeypatch.setattr(intake_mod, "_run", rec)
    result = IntakeResult(IntakeRoute.READY, "## Agent Brief\n### Summary\nthe full grounded brief",
                          "area: specific change", Complexity.DEEP, Effort.MEDIUM)
    apply_intake("owner/repo", 16, "old title", [], result)

    body = rec._edit_body()
    assert body is not None, "ready routing must edit the issue body"
    assert body.startswith("## Agent Brief")
    assert "original one-liner as filed" in body and "<details>" in body

    comment = rec._comment()
    assert comment is not None and INTAKE_MARK in comment
    assert "the full grounded brief" not in comment          # not the wall
    assert comment.count("\n") <= 8                            # short


def test_apply_intake_grill_keeps_the_full_comment_and_never_touches_the_body(monkeypatch):
    rec = _GhRecorder()
    monkeypatch.setattr(intake_mod, "_run", rec)
    result = IntakeResult(IntakeRoute.GRILL, "> *agentflow intake — generated by AI.*\n\nwhich did you mean?")
    apply_intake("owner/repo", 7, "t", [], result)

    assert rec._edit_body() is None, "a hold must not rewrite the body"
    assert "which did you mean?" in rec._comment()
