"""Test intake through its interface — the pure, fail-safe decision parser and the
label mapping. Like the reviewer: anything we cannot read as a confident build-ready
decision must fall back to holding for a human, never an accidental `ready`.
"""

import json
from types import SimpleNamespace

import pytest

from agentflow import intake as intake_mod
from agentflow.intake import (INTAKE_MARK, IntakeResult, IntakeRoute, apply_intake,
                              awaiting_recheck, compose_ready_body, intake_labels,
                              parse_intake, replies_since_intake, sweep_legacy_labels)
from agentflow.runner import Complexity, Effort


def test_ready_with_all_fields_is_build_ready():
    v = parse_intake('{"route": "ready", "title": "ISF: widen the measurement window", '
                     '"complexity": "standard", "effort": "high", "body": "## Agent Brief\\n..."}')
    assert v.route is IntakeRoute.READY and v.parsed
    assert v.complexity is Complexity.STANDARD and v.effort is Effort.HIGH
    assert v.title == "ISF: widen the measurement window" and v.body.startswith("## Agent Brief")


def test_ready_missing_complexity_defaults_deep():
    # A bigger model is the safe sizing miss — never a wrong build.
    v = parse_intake('{"route": "ready", "body": "brief", "effort": "low"}')
    assert v.route is IntakeRoute.READY and v.complexity is Complexity.DEEP


def test_ready_missing_effort_defaults_medium():
    assert parse_intake('{"route": "ready", "body": "b", "complexity": "deep"}').effort is Effort.MEDIUM


def test_grill_and_mockup_routes():
    assert parse_intake('{"route": "grill", "body": "which did you mean?"}').route is IntakeRoute.GRILL
    assert parse_intake('{"route": "mockup", "body": "kickoff"}').route is IntakeRoute.MOCKUP


def test_unknown_route_holds_for_human():
    v = parse_intake('{"route": "merge-it", "body": "x"}')
    assert v.route is IntakeRoute.GRILL and v.parsed is False


def test_ready_without_a_body_holds():
    assert parse_intake('{"route": "ready", "body": "   ", "complexity": "deep"}').parsed is False


def test_non_object_payload_holds():
    v = parse_intake('["ready"]')
    assert v.route is IntakeRoute.GRILL and v.parsed is False


def test_prose_then_fenced_json_is_parsed():
    payload = 'Here you go:\n```json\n{"route": "grill", "body": "which did you mean?"}\n```\n'
    assert parse_intake(payload).route is IntakeRoute.GRILL


def test_prose_then_bare_json_object_is_recovered():
    # The real dry-run failure: the model reasons, then emits a bare (unfenced) JSON
    # object with \n-escaped body. parse must recover the decision, not choke on prose.
    payload = ("The premise doesn't hold - truncate already exists.\n\n"
               "It shipped in #4 with tests, so there is nothing to build.\n\n"
               '{"route": "grill", "title": "truncate: clarify the cap", '
               '"body": "> *agentflow intake*\\n\\n**Already built.** Which did you mean?"}')
    v = parse_intake(payload)
    assert v.route is IntakeRoute.GRILL and v.parsed
    assert "Already built" in v.body and v.title.startswith("truncate")


def test_prose_then_json_ready_recovers_dials():
    payload = ('Grounded against the code; a clean add.\n'
               '{"route":"ready","body":"## Brief","complexity":"deep","effort":"high"}')
    v = parse_intake(payload)
    assert v.route is IntakeRoute.READY and v.complexity is Complexity.DEEP and v.effort is Effort.HIGH


def test_last_json_object_wins_over_an_example_in_prose():
    payload = ('For example I might answer {"route": "ready", "body": "x"} but actually\n'
               '{"route": "grill", "body": "the real question"}')
    v = parse_intake(payload)
    assert v.route is IntakeRoute.GRILL and v.body == "the real question"


# fail-safe: whatever the input, intake never raises and never invents a `ready`
@pytest.mark.parametrize("payload", ["", "null", "5", "not json", '{"route": 5}',
                                     '{"route": "ready"}', '{"body": "x"}', '{"route"}'])
def test_parse_never_raises_and_holds(payload):
    assert parse_intake(payload).route is IntakeRoute.GRILL


def test_labels_for_ready_carry_both_dials():
    r = parse_intake('{"route": "ready", "body": "b", "complexity": "deep", "effort": "extra"}')
    assert intake_labels(r) == ["ready-for-agent", "agentflow:complexity:deep", "agentflow:effort:extra"]


def test_labels_for_holds_are_a_single_state():
    assert intake_labels(parse_intake('{"route": "grill", "body": "q"}')) == ["agentflow:needs-grilling"]
    assert intake_labels(parse_intake('{"route": "mockup", "body": "m"}')) == ["agentflow:needs-mockup"]


def _c(body, author=None):
    c = {"body": body}
    if author is not None:
        c["author"] = {"login": author}
    return c


def test_awaiting_recheck_true_when_maintainer_replied_last():
    comments = [_c("> *agentflow intake — generated by AI.*\n\nwhich did you mean?"),
                _c("option a, keep it simple")]
    assert awaiting_recheck(comments) is True


def test_awaiting_recheck_false_when_intake_spoke_last():
    comments = [_c("some human note"),
                _c("> *agentflow intake — generated by AI.*\n\nsharpened question?")]
    assert awaiting_recheck(comments) is False


def test_awaiting_recheck_false_without_comments():
    assert awaiting_recheck([]) is False
    assert awaiting_recheck([_c("   ")]) is False


def test_replies_since_intake_collects_only_the_new_answer():
    comments = [_c("> *agentflow intake — generated by AI.*\n\nold questions"),
                _c("answer one"), _c("answer two")]
    assert replies_since_intake(comments) == "answer one\n\nanswer two"


# --- quote-reply stripping -------------------------------------------------------

_INTAKE_COMMENT = "> *agentflow intake — generated by AI.*\n\nwhich did you mean?"
_QUOTE_REPLY = ("> > *agentflow intake — generated by AI.*\n>\n> which did you mean?\n\noption a")


def test_awaiting_recheck_true_for_quote_reply():
    # Before fix this would return False — the quoted marker fooled the check.
    comments = [_c(_INTAKE_COMMENT), _c(_QUOTE_REPLY)]
    assert awaiting_recheck(comments) is True


def test_awaiting_recheck_false_for_bare_intake_comment():
    # Pure intake comment (no real reply from maintainer) must still be False.
    comments = [_c("some text"), _c(_INTAKE_COMMENT)]
    assert awaiting_recheck(comments) is False


def test_replies_since_intake_returns_full_text_of_quote_reply():
    # The maintainer's full body (including the quoted section) survives extraction.
    comments = [_c(_INTAKE_COMMENT), _c(_QUOTE_REPLY, author="owner")]
    result = replies_since_intake(comments, allowlist={"owner"})
    assert "option a" in result
    assert result.strip() == _QUOTE_REPLY.strip()


def test_replies_since_intake_cut_point_sees_through_quoted_marker():
    # A comment that only quotes our marker (no new text) is NOT the cut point —
    # scan continues past it looking for our real intake comment.
    only_quoted = "> > *agentflow intake — generated by AI.*\n>\n> some context"
    comments = [_c(_INTAKE_COMMENT), _c(only_quoted, author="owner"), _c("answer", author="owner")]
    result = replies_since_intake(comments, allowlist={"owner"})
    assert "answer" in result


# --- allowlist filtering ---------------------------------------------------------

def test_awaiting_recheck_skips_non_allowlisted_author():
    # A drive-by comment must be invisible — it should not count as a maintainer reply.
    comments = [_c(_INTAKE_COMMENT), _c("option a, keep it simple", author="stranger")]
    assert awaiting_recheck(comments, allowlist={"owner"}) is False


def test_awaiting_recheck_true_for_allowlisted_author():
    comments = [_c(_INTAKE_COMMENT), _c("option a, keep it simple", author="owner")]
    assert awaiting_recheck(comments, allowlist={"owner"}) is True


def test_awaiting_recheck_none_allowlist_does_not_filter():
    # allowlist=None is backwards-compatible: any author counts.
    comments = [_c(_INTAKE_COMMENT), _c("option a", author="stranger")]
    assert awaiting_recheck(comments, allowlist=None) is True


def test_replies_since_intake_omits_non_allowlisted():
    comments = [_c(_INTAKE_COMMENT), _c("bot spam", author="bot"), _c("real answer", author="owner")]
    result = replies_since_intake(comments, allowlist={"owner"})
    assert "real answer" in result
    assert "bot spam" not in result


# --- the brief lands in the body (issue #16) -------------------------------------

def test_compose_ready_body_puts_brief_on_top_original_below():
    body = compose_ready_body("## Agent Brief\nthe scope", "the one-line as-filed text")
    assert body.startswith("## Agent Brief")
    # the as-filed text survives, under a collapsed block below the brief
    assert "<details>" in body and "the one-line as-filed text" in body
    assert body.index("## Agent Brief") < body.index("<details>")


def test_compose_ready_body_updates_in_place_on_reintake():
    # A second intake replaces the brief but must NOT nest the old brief or add a
    # second <details> — the true original stays preserved exactly once.
    first = compose_ready_body("## Brief v1", "the one-line as-filed text")
    second = compose_ready_body("## Brief v2", first)
    assert second.startswith("## Brief v2") and "## Brief v1" not in second
    assert second.count("<details>") == 1
    assert second.count("the one-line as-filed text") == 1


class _GhRecorder:
    """Capture the gh commands apply_intake runs, and answer its body fetch."""

    def __init__(self, current_body=""):
        self.calls = []
        self.current_body = current_body

    def __call__(self, cmd, cwd=None):
        self.calls.append(cmd)
        if "issue" in cmd and "view" in cmd:
            return SimpleNamespace(returncode=0, stdout=json.dumps({"body": self.current_body}))
        return SimpleNamespace(returncode=0, stdout="")

    def _edit_body(self):
        for c in self.calls:
            if "edit" in c and "--body" in c:
                return c[c.index("--body") + 1]
        return None

    def _comment(self):
        for c in self.calls:
            if "comment" in c and "--body" in c:
                return c[c.index("--body") + 1]
        return None


def test_apply_intake_ready_writes_brief_to_body_and_a_short_comment(monkeypatch):
    rec = _GhRecorder(current_body="original one-liner as filed")
    monkeypatch.setattr(intake_mod, "_run", rec)
    result = IntakeResult(IntakeRoute.READY, "## Agent Brief\n### Summary\nthe full grounded brief",
                          "area: specific change", Complexity.DEEP, Effort.MEDIUM)
    apply_intake("owner/repo", 16, "old title", [], result)

    body = rec._edit_body()
    assert body is not None, "ready routing must edit the issue body"
    assert body.startswith("## Agent Brief")
    assert "original one-liner as filed" in body and "<details>" in body

    comment = rec._comment()
    assert comment is not None and INTAKE_MARK in comment
    assert "the full grounded brief" not in comment          # not the wall
    assert comment.count("\n") <= 8                            # short


def test_apply_intake_grill_keeps_the_full_comment_and_never_touches_the_body(monkeypatch):
    rec = _GhRecorder()
    monkeypatch.setattr(intake_mod, "_run", rec)
    result = IntakeResult(IntakeRoute.GRILL, "> *agentflow intake — generated by AI.*\n\nwhich did you mean?")
    apply_intake("owner/repo", 7, "t", [], result)

    assert rec._edit_body() is None, "a hold must not rewrite the body"
    assert "which did you mean?" in rec._comment()


# --- no-spam: nothing-new, idempotence, infra failures (issue #23) ----------------

def test_nothing_new_route_parses_without_a_body():
    # A resume that found nothing genuinely open needs no body — it must not fall back to
    # a fail-safe hold just because the body is empty.
    v = parse_intake('{"route": "nothing-new"}')
    assert v.route is IntakeRoute.NOTHING_NEW and v.parsed


class _GhSpy:
    """Records every gh command and answers the comments/body fetches with a canned tail."""

    def __init__(self, latest_comment="", current_body=""):
        self.calls = []
        self.latest_comment = latest_comment
        self.current_body = current_body

    def __call__(self, cmd, cwd=None):
        self.calls.append(cmd)
        if "view" in cmd and "comments" in cmd:
            return SimpleNamespace(returncode=0,
                                   stdout=json.dumps({"comments": [{"body": self.latest_comment}]}))
        if "view" in cmd:
            return SimpleNamespace(returncode=0, stdout=json.dumps({"body": self.current_body}))
        return SimpleNamespace(returncode=0, stdout="")

    def wrote_anything(self):
        return any(("comment" in c) or ("--add-label" in c) or ("--remove-label" in c)
                   or ("--body" in c) or ("--title" in c) for c in self.calls)


def test_apply_intake_nothing_new_writes_absolutely_nothing(monkeypatch):
    spy = _GhSpy()
    monkeypatch.setattr(intake_mod, "_run", spy)
    apply_intake("owner/repo", 5, "t", ["agentflow:needs-grilling"],
                 IntakeResult(IntakeRoute.NOTHING_NEW, ""))
    assert not spy.wrote_anything(), "a nothing-new recheck must post no comment and touch no labels"


def test_apply_intake_skips_a_re_post_of_the_same_hold(monkeypatch):
    # The exact spam vector: our last word already says this. Re-applying it changes
    # nothing, so it must post no comment and churn no labels.
    question = "> *agentflow intake — generated by AI.*\n\nwhich window did you mean?"
    spy = _GhSpy(latest_comment=question)
    monkeypatch.setattr(intake_mod, "_run", spy)
    apply_intake("owner/repo", 5, "t", ["agentflow:needs-grilling"],
                 IntakeResult(IntakeRoute.GRILL, question))
    assert not spy.wrote_anything(), "an identical re-apply must be a no-op"


def test_apply_intake_still_posts_a_genuinely_new_question(monkeypatch):
    # Idempotence must not silence a real re-post — a different question still goes out.
    spy = _GhSpy(latest_comment="> *agentflow intake — generated by AI.*\n\nold question")
    monkeypatch.setattr(intake_mod, "_run", spy)
    apply_intake("owner/repo", 5, "t", [],
                 IntakeResult(IntakeRoute.GRILL, "> *agentflow intake — generated by AI.*\n\na new question"))
    assert any("comment" in c for c in spy.calls), "a new question must still post"


def _fake_runner(launch):
    return SimpleNamespace(tool="claude", model="m", model_for=lambda c: "m",
                           prepare_worktree_detached=lambda workdir, ref, wt: None,
                           provision=lambda wt: None, launch=launch)


def test_intake_marks_a_launch_failure_as_infra_not_a_hold(tmp_path):
    runner = _fake_runner(lambda prompt, cwd, model: (False, "boom"))
    r = intake_mod.Intake(runner).intake("owner/repo", str(tmp_path),
                                         {"number": 5, "title": "t", "body": "b"})
    assert r.infra_failed is True and r.route is IntakeRoute.GRILL


def test_intake_marks_a_worktree_failure_as_infra(tmp_path, monkeypatch):
    import subprocess

    def boom(workdir, ref, wt):
        raise subprocess.CalledProcessError(1, "git worktree add")

    runner = _fake_runner(lambda *a, **k: (True, "{}"))
    runner.prepare_worktree_detached = boom
    r = intake_mod.Intake(runner).intake("owner/repo", str(tmp_path),
                                         {"number": 5, "title": "t", "body": "b"})
    assert r.infra_failed is True


# --- dial label cleanup on re-route (issue #27) ----------------------------------

def _label_edit_cmd(rec: _GhRecorder) -> list[str]:
    """The gh issue edit call that sets labels (has --add-label or just removes)."""
    for c in rec.calls:
        if "edit" in c and ("--add-label" in c or "--remove-label" in c) and "--body" not in c:
            return c
    return []


def test_apply_intake_clears_stale_dial_labels_on_reroute(monkeypatch):
    # Before fix: only STATE_LABELS were stripped; old dials accreted.
    # After fix: stale agentflow:complexity:* and agentflow:effort:* are removed too.
    rec = _GhRecorder(current_body="brief v1")
    monkeypatch.setattr(intake_mod, "_run", rec)
    result = IntakeResult(IntakeRoute.READY, "## Agent Brief v2\nnew scope",
                          "", Complexity.STANDARD, Effort.LOW)
    apply_intake("owner/repo", 7, "t",
                 ["ready-for-agent", "agentflow:complexity:deep", "agentflow:effort:medium"],
                 result)

    cmd = _label_edit_cmd(rec)
    assert cmd, "should have a label edit command"
    adds = [cmd[i + 1] for i, x in enumerate(cmd) if x == "--add-label"]
    removes = [cmd[i + 1] for i, x in enumerate(cmd) if x == "--remove-label"]

    assert "agentflow:complexity:standard" in adds
    assert "agentflow:effort:low" in adds
    assert "agentflow:complexity:deep" in removes, "stale complexity dial must be stripped"
    assert "agentflow:effort:medium" in removes, "stale effort dial must be stripped"


def test_apply_intake_unchanged_dials_not_removed(monkeypatch):
    # Re-routing with the same dials should not generate spurious --remove-label calls.
    rec = _GhRecorder(current_body="brief v1")
    monkeypatch.setattr(intake_mod, "_run", rec)
    result = IntakeResult(IntakeRoute.READY, "## Brief v2", "", Complexity.DEEP, Effort.MEDIUM)
    apply_intake("owner/repo", 9, "t",
                 ["ready-for-agent", "agentflow:complexity:deep", "agentflow:effort:medium"],
                 result)

    cmd = _label_edit_cmd(rec)
    removes = [cmd[i + 1] for i, x in enumerate(cmd) if x == "--remove-label"]
    assert "agentflow:complexity:deep" not in removes
    assert "agentflow:effort:medium" not in removes


def test_apply_intake_strips_dials_when_routing_to_hold(monkeypatch):
    # Transitioning from ready to grill should clear dial labels — they belong only on ready.
    rec = _GhRecorder()
    monkeypatch.setattr(intake_mod, "_run", rec)
    result = IntakeResult(IntakeRoute.GRILL, "> *agentflow intake*\n\nwhich did you mean?")
    apply_intake("owner/repo", 5, "t",
                 ["ready-for-agent", "agentflow:complexity:deep", "agentflow:effort:high"],
                 result)

    cmd = _label_edit_cmd(rec)
    removes = [cmd[i + 1] for i, x in enumerate(cmd) if x == "--remove-label"]
    assert "agentflow:complexity:deep" in removes
    assert "agentflow:effort:high" in removes


# --- legacy label sweep (issue #27) ----------------------------------------------

def _fake_run_for_sweep(issues_payload: str):
    """Return a fake _run that serves the given payload for list calls."""
    calls: list[list[str]] = []

    def _run(cmd, cwd=None):
        calls.append(cmd)
        if "list" in cmd:
            return SimpleNamespace(returncode=0, stdout=issues_payload)
        return SimpleNamespace(returncode=0, stdout="")

    return _run, calls


def test_sweep_migrates_bare_grilling_label(monkeypatch):
    issues = [{"number": 1, "labels": [{"name": "needs-grilling"}]}]
    fake_run, calls = _fake_run_for_sweep(json.dumps(issues))
    monkeypatch.setattr(intake_mod, "_run", fake_run)

    changed = sweep_legacy_labels("owner/repo")

    assert len(changed) == 1 and "#1" in changed[0]
    assert "agentflow:needs-grilling" in changed[0]
    edit_calls = [c for c in calls if "edit" in c]
    assert any("--add-label" in c and "agentflow:needs-grilling" in c for c in edit_calls)
    assert any("--remove-label" in c and "needs-grilling" in c for c in edit_calls)


def test_sweep_removes_bare_when_namespaced_already_present(monkeypatch):
    # Issue already has the namespaced form — just drop the bare one, don't re-add.
    issues = [{"number": 2, "labels": [{"name": "needs-mockup"},
                                        {"name": "agentflow:needs-mockup"}]}]
    fake_run, calls = _fake_run_for_sweep(json.dumps(issues))
    monkeypatch.setattr(intake_mod, "_run", fake_run)

    changed = sweep_legacy_labels("owner/repo")

    assert len(changed) == 1
    cmd = next(c for c in calls if "edit" in c)
    assert "--remove-label" in cmd and "needs-mockup" in cmd
    assert "--add-label" not in cmd, "should not re-add the namespaced label that's already there"


def test_sweep_leaves_already_correct_and_unrelated_labels_alone(monkeypatch):
    issues = [
        {"number": 3, "labels": [{"name": "agentflow:needs-grilling"}]},  # already namespaced
        {"number": 4, "labels": [{"name": "ready-for-agent"}, {"name": "bug"}]},  # unrelated
    ]
    fake_run, calls = _fake_run_for_sweep(json.dumps(issues))
    monkeypatch.setattr(intake_mod, "_run", fake_run)

    changed = sweep_legacy_labels("owner/repo")

    assert changed == [], "nothing to change"
    edit_calls = [c for c in calls if "edit" in c]
    assert edit_calls == [], "no edits should be issued"


def test_sweep_ready_for_agent_stays_bare(monkeypatch):
    # ready-for-agent is intentionally bare (ADR 0018) — sweep must not touch it.
    issues = [{"number": 5, "labels": [{"name": "ready-for-agent"}]}]
    fake_run, calls = _fake_run_for_sweep(json.dumps(issues))
    monkeypatch.setattr(intake_mod, "_run", fake_run)

    changed = sweep_legacy_labels("owner/repo")
    assert changed == []
