"""Intake — the autonomous front of the pipe (ADR 0016).

Every open issue with no state label passes through here before it can be built, except
`wayfinder:*` planning artifacts, which stay upstream until wayfinder files build tickets.
Intake *grounds* the request (reads the code, and pulls a read-only real-data snapshot
if the repo declares one), *rewrites* it into something specific, and *routes* it to
exactly one outcome:

- `ready-for-agent` — clear as day; intake writes the build brief and stamps the two
  dials (complexity + effort, ADR 0018) so the loop can build it.
- `agentflow:needs-grilling` — a real, outcome-changing fork it can't settle from
  code/data, or a request that contradicts a recorded ADR; it posts questions in the
  *maintainer's* voice and holds (ADR 0019).
- `agentflow:needs-mockup` — a user-facing surface beyond a minor bugfix; holds for a
  `/ui-craft lock` pass.

Same shape as the reviewer: a tool-agnostic session does the grounding and emits a
decision that matches the provider-neutral `INTAKE_RESULT_SCHEMA`, enforced natively by
each CLI (Claude `--json-schema`, Codex `--output-schema`); `parse_intake` validates that
structured object into an `IntakeResult`. Parsing is **fail-safe** — anything we can't
read as a confident `ready`/`mockup` falls back to holding for a human (`grill`), never an
accidental build, and a `ready` whose complexity is missing/invalid is an explicit invalid
result rather than a silent upgrade to the deep tier.

The session coordinator owns launch. This module keeps Intake's prompt, parser, routes, and
idempotent GitHub projection; `parse_intake` and `intake_labels` are pure test surfaces.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from enum import Enum

from agentflow import github
from agentflow.runner import Complexity, Effort, MockupScope
from agentflow.shell_crib import SHELL_CRIB

# The provider-neutral shape Intake's terminal decision must match. Each runner adapter
# translates it into that CLI's native structured-output surface; the CLI enforces it, so
# the parser validates a real object rather than scavenging JSON out of free text. Optional
# dials are nullable so a hold route (grill/mockup/nothing-new) omits them while still
# satisfying providers that require every property (OpenAI-style strict schemas).
INTAKE_RESULT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "route": {"type": "string", "enum": ["ready", "grill", "mockup", "nothing-new"]},
        "title": {"type": "string"},
        "body": {"type": "string"},
        "complexity": {"type": ["string", "null"], "enum": ["standard", "deep", None]},
        "effort": {"type": ["string", "null"],
                   "enum": ["low", "medium", "high", "extra", None]},
        "mockup_scope": {"type": ["string", "null"],
                         "enum": ["local", "surface", None]},
    },
    "required": ["route", "title", "body", "complexity", "effort", "mockup_scope"],
}

_DISCLAIMER = "> *agentflow intake — generated by AI.*"
INTAKE_MARK = "agentflow intake"  # substring that identifies an intake comment we posted

# Invisible fence (renders as nothing) marking where the brief ends and the preserved
# as-filed text begins. Lets a re-intake swap the brief in place instead of stacking a
# second one — everything from this marker down is the untouched original.
_ORIGINAL_MARK = "<!-- agentflow:original-below -->"

# The thread reply on a ready routing: a short, conversational note — not the brief
# itself. The brief is a build input and lives in the description now; this comment is
# the human-facing "here's what I did" and carries the intake marker so resume still
# keys off it.
_READY_COMMENT = (
    f"{_DISCLAIMER}\n\n"
    "Grounded and scoped this — the full Agent Brief is in the description now, so the "
    "build and review read straight from it. Your issue as filed is preserved under a "
    "collapsed block at the bottom. Take a look, and reply here if any of the scope is off."
)


class IntakeRoute(str, Enum):
    READY = "ready"     # build-ready — write the brief, stamp dials, proceed
    GRILL = "grill"     # hold: a real fork only the human can settle
    MOCKUP = "mockup"   # hold: needs a locked visual spec first
    NOTHING_NEW = "nothing-new"  # resume found nothing genuinely open changed — stay quiet


@dataclass(frozen=True, slots=True)
class IntakeResult:
    route: IntakeRoute
    body: str                        # the brief / questions / mockup kickoff to post
    title: str = ""                  # rewritten title ("" = leave as filed)
    complexity: Complexity | None = None
    effort: Effort | None = None
    mockup_scope: MockupScope | None = None  # local|surface — only on a mockup route
    parsed: bool = True
    detail: str = ""
    infra_failed: bool = False       # a worktree/provision/launch failure, not a model decision
    hardening: str = ""              # what the attack rounds did to this brief before it was
                                     # published (ADR 380) — appended to the ready comment, so it
                                     # is part of the comment the durability proof matches


def _held(detail: str) -> IntakeResult:
    """Fail-safe: an intake we can't read as confident-ready holds for the human."""
    body = (f"{_DISCLAIMER}\n\nI couldn't ground this into a confident scope on my own. "
            "Let's settle it together — reply here with what you meant, or run "
            "`/agentflow pickup` to drive it live.")
    return IntakeResult(IntakeRoute.GRILL, body, parsed=False, detail=detail)


def held_build_result(status: str, where: str) -> IntakeResult:
    """The hold a stuck build hands back — routes the issue to `needs-grilling` instead of
    leaving it `ready-for-agent`, where the loop would re-pick it every cycle: a fresh build
    session, a duplicate bail comment, and a duplicate ping per cycle, with the rest of the
    queue stalled behind it (ADR 0021's claim only covers a *live* build). The body carries
    the intake marker, so a maintainer reply resumes it through the normal re-intake path
    (ADR 0019). Pure (test surface)."""
    body = (f"{_DISCLAIMER}\n\nThe build stopped before opening a PR ({status}) — details in "
            f"{where}. I've held this rather than retrying blind. Reply here with what's "
            "missing (or run `/agentflow pickup` to drive it live) and I'll re-scope and retry.")
    return IntakeResult(IntakeRoute.GRILL, body)


_NEVER_READ = "I never got to read this issue — the coding agent's provider "
_RETRY = ("reply here and I'll pick this up again, or run `/agentflow pickup` to drive it "
          "live.")

# The diagnosis + remediation for each kind of permanent provider condition (issue #342). One
# fixed body per reason: an access refusal is the only one a re-authenticate helps, a rejected
# request means the sign-in is fine, a spend ceiling is a budget the run hit, and anything we
# couldn't type says only what we know. Keyed by the typed reason the provider observation
# preserved, so a restart composes the same body and the handoff still posts exactly once.
_PROVIDER_FAILURE_COPY = {
    "access": ("refused the session outright (an expired sign-in, a billing or plan limit, or "
               "a permission problem). So there's no question waiting on you here and no "
               "product decision pending.\n\nRe-authenticate the coding agent — or check its "
               f"billing, plan, and permissions — then {_RETRY}"),
    "rejected-request": ("rejected the request itself — too large for the model, an "
                         "unrecognized model, or a request it wouldn't accept. The coding "
                         "agent's credentials are fine, and there's no product decision "
                         "pending here either.\n\nThis one needs a look at what the coding "
                         f"agent was asked to send; once that's sorted, {_RETRY}"),
    "spend": ("stopped the run at its configured spending cap before the model read anything. "
              "The coding agent's credentials are fine, and there's no product decision "
              f"pending here.\n\nRaise or reset the cap for this work, then {_RETRY}"),
    "unspecified": ("ended the session permanently, without telling us which condition it was. "
                    "So there's no question waiting on you here and no product decision "
                    "pending.\n\nThis one needs a look at the coding agent's health before it "
                    f"can run again; once it's back, {_RETRY}"),
}

# The one condition that is not the provider's at all: the machine could not carry a session, so
# the agent never got a working command line and never reached this issue (issue #386). It needs
# its own whole body rather than a tail on ``_NEVER_READ`` — nothing here is the coding agent's
# provider refusing anything, and the remedy is on the machine rather than in the issue. Fixed
# text like the others, so a restarted daemon recomposes it byte-identically.
_ENVIRONMENT_FAILURE = (
    "I never got as far as reading this issue — the machine that runs the coding agent couldn't "
    "give it a working command line, so the session stopped before it could look at anything. "
    "Nothing here is waiting on a decision from you, the issue itself is fine, and no amount of "
    "retrying would have helped.\n\nThis is almost always too many leftover session checkouts "
    "piling up in the repository: past a point, the safety rules the coding agent passes to "
    "every command grow larger than the operating system will accept, and every session in that "
    f"repository dies on its first command. Reclaim those leftover checkouts, then {_RETRY}")


def _provider_failed(detail: str, reason: str = "unspecified") -> IntakeResult:
    """A *permanent* condition stopped the session before the model ever read the issue (issue
    #328). There is no product decision waiting, so the handoff names the failure and its
    remediation instead of asking the human to settle a scope question that was never asked.
    ``reason`` says *which* condition it was, so a rejected request or a spend ceiling isn't
    misdiagnosed as an expired sign-in (issue #342), and an environment that couldn't carry a
    session at all names the machine rather than blaming the coding agent's provider (issue
    #386); an unknown reason falls back to the neutral body that prescribes no wrong remedy. The
    route stays ``GRILL`` so the held state label and the durable-handoff marker machinery are
    unchanged; each body is fixed text for its reason so a restarted daemon re-detects the same
    marker."""
    if reason == "environment":
        body = _ENVIRONMENT_FAILURE
    else:
        body = _NEVER_READ + _PROVIDER_FAILURE_COPY.get(
            reason, _PROVIDER_FAILURE_COPY["unspecified"])
    return IntakeResult(IntakeRoute.GRILL, f"{_DISCLAIMER}\n\n{body}",
                        parsed=False, detail=detail, infra_failed=True)


def _infra_failed(detail: str) -> IntakeResult:
    """An *infrastructure* failure — the worktree, provision, or launch fell over before
    the model ever weighed in. Unlike a model-level hold this is not the issue's fault, so
    the loop retries it silently next cycle rather than spending the issue's state on a
    spammy hold (ADR 0019 — no spam). The body is only ever posted if the loop's bounded
    backstop fires after a run of consecutive failures."""
    body = (f"{_DISCLAIMER}\n\nI keep hitting a setup problem before I can even start "
            "grounding this — it's on my end, not your issue. I'll keep retrying; flagging "
            "it here in case it needs a look.")
    return IntakeResult(IntakeRoute.GRILL, body, parsed=False, detail=detail, infra_failed=True)


def _enum_or_none(enum, raw):
    try:
        return enum(str(raw).strip().lower())
    except ValueError:
        return None


def parse_intake(payload: str) -> IntakeResult:
    """Validate a grounding session's structured decision. Pure, fail-safe (test surface).

    The CLI enforces `INTAKE_RESULT_SCHEMA` natively, so the payload is the decision object
    itself — parsed strictly, never scavenged out of reasoning prose. A confident `ready`
    needs a valid route, a non-empty body, and a valid complexity: a missing/invalid
    complexity is an explicit invalid result, never a silent upgrade to the deep tier
    (effort still softens to `medium`, since it only guides work, not model size). Anything
    unreadable → held for a human. Never raises.
    """
    try:
        data = json.loads(payload.strip() or "null")
        if not isinstance(data, dict):
            return _held("intake output was not a structured decision object")
        route = _enum_or_none(IntakeRoute, data.get("route"))
        if route is None:
            return _held("intake decision carried no valid route")
        if route is IntakeRoute.NOTHING_NEW:
            return IntakeResult(route, "")  # a no-op resume: no body, nothing to post
        body = str(data.get("body", "")).strip()
        if not body:
            return _held("intake decision carried no body")
        title = str(data.get("title", "")).strip()
        if route is IntakeRoute.READY:
            complexity = _enum_or_none(Complexity, data.get("complexity"))
            if complexity is None:
                return _held("ready intake carried no valid complexity")
            effort = _enum_or_none(Effort, data.get("effort")) or Effort.MEDIUM
            return IntakeResult(route, body, title, complexity, effort)
        if route is IntakeRoute.MOCKUP:
            # Scope is fail-safe to `local` per ADR 0048: an unknown/missing/invalid value
            # never reopens the whole visual world, only the narrower addition.
            scope = _enum_or_none(MockupScope, data.get("mockup_scope")) or MockupScope.LOCAL
            return IntakeResult(route, body, title, mockup_scope=scope)
        return IntakeResult(route, body, title)
    except Exception as e:  # noqa: BLE001 — fail-safe, never propagate
        return _held(f"parse error: {type(e).__name__}")


def compose_ready_body(brief: str, current_body: str) -> str:
    """The issue body after a ready routing: the Agent Brief on top, the as-filed text
    preserved verbatim under a collapsed `<details>` at the bottom (ADR 0016/0022 — the
    brief must live where builder and reviewer read it). Pure (test surface).

    Idempotent on re-intake: if `current_body` already carries a composed brief (the
    `_ORIGINAL_MARK` fence), the previously-preserved original is kept exactly as-is and
    only the brief above it is replaced — never a second `<details>`, never the old brief
    nested inside the new one."""
    brief = brief.strip()
    idx = current_body.find(_ORIGINAL_MARK)
    if idx != -1:
        return f"{brief}\n\n{current_body[idx:].strip()}"
    original = current_body.strip() or "_(no description as filed)_"
    return (f"{brief}\n\n{_ORIGINAL_MARK}\n<details>\n<summary>Original issue as filed</summary>"
            f"\n\n{original}\n\n</details>")


def _ready_body_has_envelope(body: str) -> bool:
    """Whether ``body`` has one complete generated original-text envelope."""
    index = body.find(_ORIGINAL_MARK)
    if index <= 0 or body.count(_ORIGINAL_MARK) != 1:
        return False
    tail = body[index:]
    opening = (f"{_ORIGINAL_MARK}\n<details>\n"
               "<summary>Original issue as filed</summary>\n\n")
    return tail.startswith(opening) and tail.endswith("\n\n</details>")


def _ready_body_is_canonical(body: str, brief: str) -> bool:
    """Whether the exact requested brief precedes one complete original-text envelope."""
    return (body.startswith(f"{brief.strip()}\n\n{_ORIGINAL_MARK}")
            and _ready_body_has_envelope(body))


def intake_labels(result: IntakeResult) -> list[str]:
    """The labels to stamp for a routed issue — exactly one state, plus dials when
    ready. Pure (test surface)."""
    if result.route is IntakeRoute.READY:
        return ["ready-for-agent",
                f"agentflow:complexity:{result.complexity.value}",
                f"agentflow:effort:{result.effort.value}"]
    if result.route is IntakeRoute.MOCKUP:
        scope = result.mockup_scope or MockupScope.LOCAL
        return ["agentflow:needs-mockup", f"agentflow:mockup:{scope.value}"]
    return ["agentflow:needs-grilling"]


_DOUBLE_QUOTED_RE = re.compile(r"^>\s*>", re.MULTILINE)


def _strip_quoted_lines(body: str) -> str:
    """Remove re-quoted lines (starting with '> >') so a GitHub quote-reply of our
    comment doesn't mask our marker. Our marker lives on a single-'>' line in our
    posts — those are kept so we can still detect our own comments."""
    return "\n".join(
        line for line in body.splitlines() if not _DOUBLE_QUOTED_RE.match(line)
    )


def awaiting_recheck(comments: list[dict], allowlist: set[str] | None = None) -> bool:
    """True when a held issue's most recent non-empty comment from an allowlisted author
    is the maintainer's reply — i.e. they answered and it's our move again (ADR 0019).
    False when the last word is ours, or there are no qualifying comments. Pure.

    Quote-reply lines (starting with '>') are stripped before scanning so a maintainer
    who quotes our comment still counts as a reply, not as us. Comments from authors not
    in *allowlist* are skipped entirely; *allowlist=None* disables the author filter."""
    for c in reversed(comments):
        body = c.get("body", "").strip()
        if not body:
            continue
        if allowlist is not None and c.get("author", {}).get("login", "") not in allowlist:
            continue
        return INTAKE_MARK not in _strip_quoted_lines(body)
    return False


def replies_since_intake(comments: list[dict], allowlist: set[str] | None = None) -> str:
    """The maintainer's comment(s) after our last intake comment — their answer text.
    Pure (test surface).

    Quote-reply lines are stripped before scanning for the cut point so a maintainer
    quote-reply is not mistaken for our marker. Only comments from *allowlist* authors
    are collected; *allowlist=None* collects all (backwards-compatible)."""
    tail = []
    for c in reversed(comments):
        if INTAKE_MARK in _strip_quoted_lines(c.get("body", "")):
            break
        if allowlist is not None and c.get("author", {}).get("login", "") not in allowlist:
            continue
        tail.append(c.get("body", "").strip())
    return "\n\n".join(b for b in reversed(tail) if b)


# The three state labels intake owns — kept mutually exclusive on an issue.
STATE_LABELS = ("ready-for-agent", "agentflow:needs-grilling", "agentflow:needs-mockup")

# Dial label prefixes — cleared when stamping new dials (or dropping to a hold route).
_DIAL_PREFIXES = ("agentflow:complexity:", "agentflow:effort:")

# Every single-valued prefixed label intake manages: the dials plus the mockup scope
# (ADR 0048). A re-route leaves exactly one of each, so any managed label not in the new
# set is stale and cleared — a mockup→ready promotion drops the scope with the dials.
_MANAGED_PREFIXES = _DIAL_PREFIXES + ("agentflow:mockup:",)

# Bare pre-enrollment vocabulary → agentflow:* canonical form.
# Note: ready-for-agent stays bare (ADR 0018 — settled; excluded from this map).
_LEGACY_LABEL_MAP: dict[str, str] = {
    "needs-grilling": "agentflow:needs-grilling",
    "needs-mockup": "agentflow:needs-mockup",
}

_LABEL_COLORS = {
    "ready-for-agent": "0e8a16",
    "agentflow:needs-grilling": "d93f0b",
    "agentflow:needs-mockup": "f9d0c4",
    "agentflow:mockup:local": "fbca04",
    "agentflow:mockup:surface": "e99695",
    "agentflow:complexity:standard": "1d76db",
    "agentflow:complexity:deep": "0052cc",
    "agentflow:effort:low": "c5def5",
    "agentflow:effort:medium": "5319e7",
    "agentflow:effort:high": "b60205",
    "agentflow:effort:extra": "006b75",
}


def _fill(template: str, **kw: str) -> str:
    """Substitute {name} placeholders without str.format — brace-safe against issue
    bodies that contain literal `{`/`}` (code snippets, JSON)."""
    out = template
    for k, v in kw.items():
        out = out.replace("{" + k + "}", str(v))
    return out


INTAKE_PROMPT = """You are agentflow's intake for {repo} issue #{n}. You turn one freshly-filed,
often-vague issue into a single decision. You are unattended — nobody is here to answer — so
you act on your best judgment, never by asking, EXCEPT where a genuine fork needs the human.

YOUR ONLY OUTPUT IS THE JSON DECISION described at the end. Do NOT write to GitHub yourself:
do not edit the issue title, do not post or edit comments, do not add or remove labels. The
harness reads your JSON and applies all of that for you — if you also do it, the issue gets a
duplicate title change and a duplicate comment. The "rewrite the title" and "write the body"
steps below mean *put those values in the JSON*, not run `gh`. The only commands you run are
READ-ONLY grounding (reading code, the read-only data pull).

The issue as filed:
Title: {title}
---
{body}
---

GROUND IT FIRST — do the work, don't guess:
- Read the code in this checkout deeply enough to know where the change would live and whether
  the premise even holds. Cite what you found.
- If this repo's AGENTS.md / CLAUDE.md declares a read-only real-data pull (e.g. ciq's
  `ciq-pull-db` -> a readonly snapshot), RUN IT and check the real numbers. Read-only only:
  never touch live/authoritative data, never write code here.
- Verify the claim. If it's already implemented, or the premise doesn't hold (e.g. the numbers
  moved), say so with the evidence — that is a hold, not a build.

THEN CHOOSE ONE ROUTE:
- "ready" — clear as day after grounding: you know exactly what to build and nothing material is
  left to decide. Only route here when a confident, well-scoped build is possible.
- "mockup" — it needs a user-facing surface beyond a minor bugfix; the visual/interaction design
  must be locked first.
- "grill" — a real choice remains that CHANGES THE RESULT and you can't settle it from the code
  or data, OR the request contradicts a recorded decision (an ADR), OR the premise is wrong / the
  intent is unclear. Hold for the human. Do NOT grill over small uncertainties you can reasonably
  decide — scope those and proceed.

REWRITE the title to be specific: "<area/surface>: <specific behavior or change>".

WRITE the body for your route (Markdown), starting with this exact line:
{disclaimer}

- ready -> an Agent Brief with these sections: **Summary**; **Verified** (re-derive the claim
  against named functions/branches on the real data — quote the numbers); **Current behavior**
  (grounded numbers); **Desired behavior**; **Key interfaces** (where the change lives — say
  "explore fresh; pointers, not line numbers", and name any traps); **Interface shape** (one or
  two sentences on what the caller-facing front door should look like, judged by the charter's
  depth test; if the change is purely internal to an existing interface, say so instead of
  omitting the section); **Acceptance criteria** (a checkbox list; bake grounded numeric literals
  in where they apply, and include a test that would fail if the bug regressed); **Out of scope**
  (explicit don'ts).
- grill -> questions IN THE MAINTAINER'S VOICE: talk about the app's behavior and their real
  numbers, NEVER about code symbols, ADR numbers, or file paths. Lead with the symptom/impact,
  give 2-3 concrete options grounded in real examples, and say which you'd pick and why. Max 5.
- mockup -> a short `/ui-craft lock` kickoff: name the one surface in scope, STATE THE SCOPE
  you chose (local vs surface — see MOCKUP SCOPE below), and give the concept axes to explore
  (a `surface` round: 3-4 wildly-different whole-surface concepts; a `local` round: a few ways
  the ADDITION itself could work, inside the shipping surface's existing identity).

MOCKUP SCOPE (only for "mockup") — classify how wide this reopens the visual world:
- "local" — an ADDITION inside an already-shipping surface (a new panel, control, row, state).
  Inherit that surface's identity; vary only what the addition introduces. The DEFAULT when
  uncertain — do not reopen the whole surface for a contained addition.
- "surface" — a whole-surface replacement or a brand-new surface with no incumbent to inherit.
  Keep the open 3-4 genuinely-different-concept tournament.

DIALS (only for "ready"):
- complexity: "standard" (ordinary logic -> sonnet/Terra) or "deep" (correctness-sensitive,
  design-heavy -> opus/Sol). If this repo is correctness-sensitive (e.g. medical), lean deep.
- effort: "low" | "medium" | "high" | "extra" — anchor to real merged-PR history, not the
  ask's brevity or a scary-sounding subsystem name:
  - low: one focused fix, a handful of files (~70-line diff, ~3 files) — the #240 class.
  - medium: a contained feature or fix with tests, a few files (~180 lines, ~4 files).
  - high: cross-module design work (~390 lines, ~8 files, the long-tail builds) — the #208 class.
  - extra: subsystem-scale — experiment rigs, migrations (1800+ lines, ~25 files) — the #228 class.
  Rate the blast radius of the change, not the brevity of the ask (#220/#27 read low but landed
  ~230-270 lines). A scary subsystem name doesn't make the change big (#119/#112 were rated high
  but landed ~80-150 lines). The dial now also sets builder reasoning depth (ADR 0046) — over-
  rating burns real capacity, so don't round up "to be safe".

Your final response IS the decision as a structured object — the harness enforces its
schema natively, so you do not hand-write or fence the JSON; just produce these fields:
- "route": "ready" | "grill" | "mockup"
- "title": the rewritten title
- "body": the Markdown to post (put all human-facing prose here)
- "complexity": "standard" | "deep" — REQUIRED for "ready"; null for a hold
- "effort": "low" | "medium" | "high" | "extra" — for "ready"; null for a hold
- "mockup_scope": "local" | "surface" — REQUIRED for "mockup" (default "local" when unsure);
  null for every other route
For "grill" set complexity, effort, and mockup_scope to null; for "ready" set mockup_scope
to null; for "mockup" set complexity and effort to null.""" + SHELL_CRIB


_IMAGE_HANDOFF = (
    "\n\nThis issue's description carries one or more image attachments (screenshots). They "
    "have been downloaded into `{dir}/` in your worktree — list that directory and Read every "
    "image file so you SEE what the screenshot shows and ground your route on its actual "
    "content, not just the surrounding text. A screenshot with no prose is a real report, not "
    "an unreadable one — do not hold it as vague solely because the body has little text; read "
    "the picture first. If that directory is empty or missing, the download did not succeed — "
    "proceed with the text you have.")


_OWNER_COMMENTS = (
    "\n\nMAINTAINER COMMENTS posted after filing — these are authoritative: where a comment "
    "narrows, redirects, or defers scope stated in the body, the comment wins. Ground your route "
    "on the *current* intent.\n---\n{comments}\n---")


def intake_prompt(repo: str, issue: dict, extra: str = "", comments: str = "") -> str:
    """The durable provider input for one Intake stage.

    ``comments`` are maintainer comments the issue picked up after it was filed, on a *fresh*
    intake. An issue is often narrowed, redirected, or half-deferred in its own thread minutes
    after it is written, and reading only the body produced a confident brief for work its owner
    had already shelved. ``extra`` is the resume channel — the maintainer's answer to an earlier
    hold — and carries its own framing; the caller supplies one or the other, never both, so this
    stays one rule per input: append each section if it has anything in it.
    """
    from agentflow.intake_attachments import ATTACHMENTS_DIRNAME, extract_image_urls
    body = issue.get("body") or ""
    prompt = _fill(INTAKE_PROMPT, repo=repo, n=str(issue["number"]), disclaimer=_DISCLAIMER,
                   title=issue.get("title", ""), body=body or "(no description)")
    if extract_image_urls(body):
        prompt += _IMAGE_HANDOFF.replace("{dir}", ATTACHMENTS_DIRNAME)
    if comments:
        prompt += _OWNER_COMMENTS.replace("{comments}", comments)
    if extra:
        prompt += ("\n\nTHE MAINTAINER HAS REPLIED to your earlier hold — treat this as their "
                   "answer or waiver: promote to ready if the issue is now settled (they answered "
                   "your questions, waived the visual spec requirement, or pointed at a locked spec), "
                   "else re-post ONLY what's still open. "
                   "IF this issue was held for a MOCKUP and a variant round was already drawn (a "
                   "comment on the issue naming variants A/B/C/D with screenshots), the reply may be "
                   "a PICK — \"B\", \"the second one\", \"A but tighter\". In that case: read that "
                   "mockup comment (it links the committed variant files on a mockup branch and "
                   "carries each variant's `LOCKED` contract inline), map the pick to its variant, "
                   "and route \"ready\" with a brief that (a) records the EXACT committed mockup path "
                   "and branch for the chosen variant, and (b) copies that variant's `LOCKED` contract "
                   "VERBATIM into the brief under a `## LOCKED visual contract` heading — word for word, "
                   "no paraphrase or trimming — so review stays self-contained after the mockups are "
                   "archived (ADR 0018/0048 — the build's screenshots are judged against this contract, "
                   "not just the committed file). A request for a DIFFERENT or fresh set is NOT a pick — "
                   "re-hold (route \"mockup\") as a follow-up; never auto-loop a new variant round. "
                   'If nothing genuinely open changed — the reply was chit-chat, or it didn\'t move '
                   'any open question — answer route "nothing-new" (no body) and I\'ll stay quiet '
                   "rather than restate myself.\n"
                   f"---\n{extra}\n---")
    return prompt


_REDRAFT = """

YOUR DRAFT WAS ATTACKED. Nothing has been published — the issue is untouched and the maintainer
has seen none of this. You drafted the plan below, a cold session with no memory of your reasoning
tried to break it, and these are its objections. This is round {round} of at most {max_rounds};
answer them and hand back your best plan.

Your draft:
Title: {draft_title}
---
{draft_body}
---

Its objections:
---
{objections}
---

HOW TO ANSWER:
- Where an objection lands, FIX THE PLAN. Re-ground it against the code first — the attacker may
  be wrong about the code too, and adopting a wrong correction is worse than the original claim.
- Where an objection does not land, keep your plan and say why in one line under a
  `## Answered objections` heading at the end of the brief. Standing your ground on evidence is a
  correct answer; folding to every objection is not.
- If the objections expose a genuine fork that only the maintainer can settle — a real choice that
  CHANGES THE RESULT and no amount of reading the code decides — route "grill" and ask them. That
  is not a failure; it is the one thing this whole exercise is for. Do not grill over something you
  can decide.

Answer with a complete decision, exactly as before: the whole brief again, not a diff against your
last one. Your route may change; the dials may change."""


def redraft_prompt(base_prompt: str, draft_title: str, draft_body: str,
                   objections: str, *, round: int, max_rounds: int) -> str:
    """The durable provider input for one hardening round of intake (ADR 380). Pure.

    ``base_prompt`` is the grounding prompt the *first* draft came from, carried unchanged down
    the chain — so every redraft re-grounds from the same issue snapshot the argument started
    from, and a round replayed after a crash composes byte-identical input. It is deliberately
    the whole prompt rather than a follow-up message: this is a new session, so it has to be
    able to re-ground from nothing.
    """
    return base_prompt + _fill(
        _REDRAFT, round=str(round), max_rounds=str(max_rounds),
        draft_title=draft_title,
        draft_body=draft_body.strip() or "(no draft body)",
        objections=objections.strip() or "(no objections recorded)")


def _ensure_label(repo: str, name: str) -> None:
    """Idempotently create the label so `--add-label` can't fail on a fresh repo."""
    color = _LABEL_COLORS.get(name, "ededed")
    github.create_label(repo, name, color)


def _result_comment(result: IntakeResult) -> str:
    """The stable comment payload for one route, excluding an optional retitle preface.

    A published brief carries one extra line saying what the attack rounds did to it before it
    was posted (ADR 380). It is part of the stable payload rather than a second comment, so the
    idempotence and durability proofs keep matching exactly one comment per route.
    """
    if result.route is not IntakeRoute.READY:
        return result.body
    return f"{_READY_COMMENT}\n\n{result.hardening}" if result.hardening else _READY_COMMENT


def _comment_matches_result(body: str, result: IntakeResult) -> bool:
    """Whether a durable issue comment is this route's output.

    The first projection may include the old title as a conversational preface. A retry after
    the title mutation can no longer reconstruct that old title, so match the stable payload at
    the end while still requiring the generated retitle preface shape.
    """
    actual = body.strip()
    expected = _result_comment(result).strip()
    return actual == expected or (
        actual.startswith('> Retitled from: "') and actual.endswith(f"\n\n{expected}"))


def _result_comment_exists(repo: str, issue_number: int,
                           result: IntakeResult) -> bool | None:
    """Whether this route's comment exists, or ``None`` when GitHub is unreadable.

    Unreadable is deliberately distinct from absent: treating uncertainty as absence could
    post a duplicate while replaying a partially projected route.
    """
    comments = github.issue_comments(repo, issue_number)
    if comments is None:
        return None
    return any(_comment_matches_result(c.body, result) for c in comments)


def apply_intake(repo: str, issue_number: int, current_title: str,
                 current_labels: list[str], result: IntakeResult,
                 source_title: str | None = None,
                 source_body: str | None = None) -> str:
    """Write the decision to GitHub, then set the one state label + dials (clearing any
    other state label). Impure; returns a one-line summary.

    On `ready` the brief is a **build input**: it goes into the issue *body* (where the
    builder prompt and reviewer acceptance read it, ADR 0016/0022), the as-filed text is
    preserved below it, and the thread gets a short conversational note. On `grill` /
    `mockup` — those are conversations, not build inputs — the full text stays a comment.

    No-spam (ADR 0019): a `nothing-new` resume writes nothing at all, and an apply whose
    comment materially matches the latest comment we already posted is skipped — a
    nothing-changed recheck must not restate itself."""
    if result.route is IntakeRoute.NOTHING_NEW:
        return "nothing new — nothing to post"

    labels = intake_labels(result)
    target_title = result.title or source_title or ""
    retitled_from = current_title if (target_title and target_title != current_title) else None
    comment = _result_comment(result)
    if retitled_from is not None:
        comment = f'> Retitled from: "{retitled_from}"\n\n{comment}'

    # Idempotent across partial writes: once this route's comment exists, retries finish any
    # remaining title/body/label mutations without posting it again.
    comment_done = _result_comment_exists(repo, issue_number, result)
    if comment_done is None:
        return f"routed -> {result.route.value} deferred (comments unreadable)"
    exact_labels = set(labels).issubset(current_labels)
    stale_state = any(name in current_labels and name not in set(labels) for name in STATE_LABELS)
    stale_dials = any(any(name.startswith(p) for p in _MANAGED_PREFIXES)
                      and name not in set(labels) for name in current_labels)
    title_done = not retitled_from
    if result.route is IntakeRoute.READY:
        current_body = github.issue_body(repo, issue_number)
        if current_body is None:
            # Fail closed: we cannot compose the brief without the original to preserve.
            return f"routed -> {result.route.value} deferred (body unreadable)"
        if (source_body is None and _ORIGINAL_MARK in current_body
                and not _ready_body_has_envelope(current_body)):
            return f"routed -> {result.route.value} deferred (body envelope malformed)"
        # Coordinated Intake projects from its immutable submission snapshot. Legacy callers
        # without that source retain the old idempotent behavior over the live body.
        body_source = source_body if source_body is not None else current_body
        expected_body = compose_ready_body(result.body, body_source)
        body_done = (current_body == expected_body
                     and _ready_body_is_canonical(current_body, result.body))
    else:
        current_body = ""
        body_done = True
    if (comment_done and exact_labels and not stale_state and not stale_dials
            and title_done and body_done):
        return f"unchanged -> {result.route.value} (already posted)"

    if retitled_from is not None:
        github.edit_title(repo, issue_number, target_title)
    if result.route is IntakeRoute.READY:
        github.edit_body(repo, issue_number, expected_body)
    if not comment_done:
        github.comment(repo, issue_number, comment)

    for name in labels:
        _ensure_label(repo, name)
    new_labels_set = set(labels)
    for name in labels:
        github.add_label(repo, issue_number, name)
    for name in STATE_LABELS:  # keep exactly one state label — clear stale holds on promote
        if name not in new_labels_set and name in current_labels:
            github.remove_label(repo, issue_number, name)
    for name in current_labels:  # clear stale dials/scope — a re-route leaves exactly one of each
        if any(name.startswith(p) for p in _MANAGED_PREFIXES) and name not in new_labels_set:
            github.remove_label(repo, issue_number, name)
    tail = "" if result.parsed else " (fail-safe hold)"
    return f"routed -> {result.route.value}{tail}"


def intake_result_is_durable(repo: str, issue_number: int, result: IntakeResult,
                             source_title: str | None = None,
                             source_body: str | None = None) -> bool:
    """Verify that the routing decision is visible on GitHub before disposal."""
    if result.route is IntakeRoute.NOTHING_NEW:
        return True
    # One whole-issue snapshot: a route is only visible if title, labels, comment and body agree
    # at the same moment, so a proof assembled from separate reads would be no proof.
    issue = github.issue_view(repo, issue_number)
    if issue is None:
        return False
    labels = issue.labels
    required = set(intake_labels(result))
    if not required.issubset(labels):
        return False
    if any(name in labels and name not in required for name in STATE_LABELS):
        return False
    if any(any(name.startswith(prefix) for prefix in _MANAGED_PREFIXES)
           and name not in required for name in labels):
        return False
    expected_title = result.title or source_title
    if expected_title is not None and issue.title != expected_title:
        return False
    if not any(_comment_matches_result(comment.body, result) for comment in issue.comments):
        return False
    if result.route is IntakeRoute.READY:
        # Prove the EXACT canonical composed body — the brief over the preserved original —
        # not just that the brief appears somewhere. `compose_ready_body` is idempotent on an
        # already-composed body, so the durable body must equal composing the brief over itself.
        body = issue.body
        if not _ready_body_is_canonical(body, result.body):
            return False
        if source_body is not None:
            return body == compose_ready_body(result.body, source_body)
        return True
    return True


def sweep_legacy_labels(repo: str) -> list[str]:
    """Migrate bare pre-enrollment needs-* labels to the agentflow:* vocabulary on open
    issues. Idempotent — safe to run more than once. Returns one-line change descriptions,
    one per issue touched."""
    issues = github.list_issues(repo, limit=500)
    if issues is None:
        return ["error: could not list issues"]
    changed = []
    for issue in issues:
        n = issue.number
        names = set(issue.labels)
        to_add: list[str] = []
        to_remove: list[str] = []
        for bare, namespaced in _LEGACY_LABEL_MAP.items():
            if bare in names:
                if namespaced not in names:
                    to_add.append(namespaced)
                to_remove.append(bare)
        if not to_remove:
            continue
        for name in to_add:
            _ensure_label(repo, name)
            github.add_label(repo, n, name)
        for name in to_remove:
            github.remove_label(repo, n, name)
        parts = []
        if to_add:
            parts.append(f"added {', '.join(sorted(to_add))}")
        parts.append(f"removed {', '.join(sorted(to_remove))}")
        changed.append(f"#{n}: {'; '.join(parts)}")
    return changed
