"""Intake — the autonomous front of the pipe (ADR 0016).

Every open issue with no state label passes through here before it can be built.
Intake *grounds* the request (reads the code, and pulls a read-only real-data snapshot
if the repo declares one), *rewrites* it into something specific, and *routes* it to
exactly one outcome:

- `ready-for-agent` — clear as day; intake writes the build brief and stamps the two
  dials (complexity + effort, ADR 0018) so the loop can build it.
- `agentflow:needs-grilling` — a real, outcome-changing fork it can't settle from
  code/data, or a request that contradicts a recorded ADR; it posts questions in the
  *maintainer's* voice and holds (ADR 0019).
- `agentflow:needs-mockup` — a user-facing surface beyond a minor bugfix; holds for a
  `/ui-mockups` pass.

Same shape as the reviewer: a tool-agnostic session does the grounding and emits a
strict-JSON decision; `parse_intake` turns that into an `IntakeResult`. Parsing is
**fail-safe** — anything we can't read as a confident `ready`/`mockup` falls back to
holding for a human (`grill`), never an accidental build.

Deep module: `Intake(runner).intake(...) -> IntakeResult`, then `apply_intake(...)`
writes it to GitHub. `parse_intake` and `intake_labels` are pure — the test surface.
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from agentflow.runner import Complexity, Effort, _WorktreeRunner, _run

_FENCE_RE = re.compile(r"```[a-zA-Z]*\s*\n(.*?)\n```", re.DOTALL)
_DISCLAIMER = "> *agentflow intake — generated by AI.*"
INTAKE_MARK = "agentflow intake"  # substring that identifies an intake comment we posted


class IntakeRoute(str, Enum):
    READY = "ready"     # build-ready — write the brief, stamp dials, proceed
    GRILL = "grill"     # hold: a real fork only the human can settle
    MOCKUP = "mockup"   # hold: needs a locked visual spec first


@dataclass(frozen=True, slots=True)
class IntakeResult:
    route: IntakeRoute
    body: str                        # the brief / questions / mockup kickoff to post
    title: str = ""                  # rewritten title ("" = leave as filed)
    complexity: Complexity | None = None
    effort: Effort | None = None
    parsed: bool = True
    detail: str = ""


def _held(detail: str) -> IntakeResult:
    """Fail-safe: an intake we can't read as confident-ready holds for the human."""
    body = (f"{_DISCLAIMER}\n\nI couldn't ground this into a confident scope on my own. "
            "Let's settle it together — reply here with what you meant, or run "
            "`/agentflow pickup` to drive it live.")
    return IntakeResult(IntakeRoute.GRILL, body, parsed=False, detail=detail)


def _json_objects(text: str) -> list[dict]:
    """Candidate JSON dicts from a model message, best-guess first: any fenced ```json
    blocks (last first), the whole message, then every balanced {...} object scanning
    from the end. Robust to a decision that follows the model's reasoning prose — models
    reason before they answer, so 'STRICT JSON only' is not reliable on its own."""
    text = text.strip()
    out: list[dict] = []

    def _try(s: str) -> None:
        try:
            obj = json.loads(s)
        except ValueError:
            return
        if isinstance(obj, dict):
            out.append(obj)

    for b in reversed(_FENCE_RE.findall(text)):
        _try(b.strip())
    _try(text)
    dec = json.JSONDecoder()
    for i in reversed([j for j, c in enumerate(text) if c == "{"]):
        try:
            obj, _end = dec.raw_decode(text[i:])
        except ValueError:
            continue
        if isinstance(obj, dict):
            out.append(obj)
    return out


def _enum_or_none(enum, raw):
    try:
        return enum(str(raw).strip().lower())
    except ValueError:
        return None


def parse_intake(payload: str) -> IntakeResult:
    """Parse a grounding session's JSON decision. Pure, fail-safe (test surface).

    Recovers the decision even when the model prefixes it with reasoning prose. A
    confident `ready` needs a valid route and a non-empty body; a missing/garbled
    complexity defaults to `deep` (a bigger model is the safe sizing miss, never a wrong
    build) and effort to `medium`. Anything unreadable → held for a human. Never raises.
    """
    try:
        for data in _json_objects(payload):
            route = _enum_or_none(IntakeRoute, data.get("route"))
            if route is None:
                continue  # not the decision object — try the next candidate
            body = str(data.get("body", "")).strip()
            if not body:
                return _held("intake decision carried no body")
            title = str(data.get("title", "")).strip()
            if route is IntakeRoute.READY:
                complexity = _enum_or_none(Complexity, data.get("complexity")) or Complexity.DEEP
                effort = _enum_or_none(Effort, data.get("effort")) or Effort.MEDIUM
                return IntakeResult(route, body, title, complexity, effort)
            return IntakeResult(route, body, title)
        return _held("no JSON decision with a valid route in the intake output")
    except Exception as e:  # noqa: BLE001 — fail-safe, never propagate
        return _held(f"parse error: {type(e).__name__}")


def intake_labels(result: IntakeResult) -> list[str]:
    """The labels to stamp for a routed issue — exactly one state, plus dials when
    ready. Pure (test surface)."""
    if result.route is IntakeRoute.READY:
        return ["ready-for-agent",
                f"agentflow:complexity:{result.complexity.value}",
                f"agentflow:effort:{result.effort.value}"]
    if result.route is IntakeRoute.MOCKUP:
        return ["agentflow:needs-mockup"]
    return ["agentflow:needs-grilling"]


def awaiting_recheck(comments: list[dict]) -> bool:
    """True when a held issue's most recent non-empty comment is the maintainer's reply
    — i.e. they answered and it's our move again (ADR 0019). False when the last word is
    ours, or there are no comments. Pure. The bot posts as the maintainer, so author
    can't tell us apart — we key on our own marker."""
    for c in reversed(comments):
        body = c.get("body", "").strip()
        if not body:
            continue
        return INTAKE_MARK not in body
    return False


def replies_since_intake(comments: list[dict]) -> str:
    """The maintainer's comment(s) after our last intake comment — their answer text.
    Pure (test surface)."""
    tail = []
    for c in reversed(comments):
        if INTAKE_MARK in c.get("body", ""):
            break
        tail.append(c.get("body", "").strip())
    return "\n\n".join(b for b in reversed(tail) if b)


# The three state labels intake owns — kept mutually exclusive on an issue.
STATE_LABELS = ("ready-for-agent", "agentflow:needs-grilling", "agentflow:needs-mockup")

_LABEL_COLORS = {
    "ready-for-agent": "0e8a16",
    "agentflow:needs-grilling": "d93f0b",
    "agentflow:needs-mockup": "f9d0c4",
    "agentflow:complexity:standard": "1d76db",
    "agentflow:complexity:deep": "0052cc",
    "agentflow:effort:low": "c5def5",
    "agentflow:effort:medium": "5319e7",
    "agentflow:effort:high": "b60205",
    "agentflow:effort:extra": "006b75",
}


def _fill(template: str, **kw: str) -> str:
    """Substitute {name} placeholders without str.format — brace-safe against issue
    bodies that contain literal `{`/`}` (code snippets, JSON)."""
    out = template
    for k, v in kw.items():
        out = out.replace("{" + k + "}", str(v))
    return out


INTAKE_PROMPT = """You are agentflow's intake for {repo} issue #{n}. You turn one freshly-filed,
often-vague issue into a single decision. You are unattended — nobody is here to answer — so
you act on your best judgment, never by asking, EXCEPT where a genuine fork needs the human.

YOUR ONLY OUTPUT IS THE JSON DECISION described at the end. Do NOT write to GitHub yourself:
do not edit the issue title, do not post or edit comments, do not add or remove labels. The
harness reads your JSON and applies all of that for you — if you also do it, the issue gets a
duplicate title change and a duplicate comment. The "rewrite the title" and "write the body"
steps below mean *put those values in the JSON*, not run `gh`. The only commands you run are
READ-ONLY grounding (reading code, the read-only data pull).

The issue as filed:
Title: {title}
---
{body}
---

GROUND IT FIRST — do the work, don't guess:
- Read the code in this checkout deeply enough to know where the change would live and whether
  the premise even holds. Cite what you found.
- If this repo's AGENTS.md / CLAUDE.md declares a read-only real-data pull (e.g. ciq's
  `ciq-pull-db` -> a readonly snapshot), RUN IT and check the real numbers. Read-only only:
  never touch live/authoritative data, never write code here.
- Verify the claim. If it's already implemented, or the premise doesn't hold (e.g. the numbers
  moved), say so with the evidence — that is a hold, not a build.

THEN CHOOSE ONE ROUTE:
- "ready" — clear as day after grounding: you know exactly what to build and nothing material is
  left to decide. Only route here when a confident, well-scoped build is possible.
- "mockup" — it needs a user-facing surface beyond a minor bugfix; the visual/interaction design
  must be locked first.
- "grill" — a real choice remains that CHANGES THE RESULT and you can't settle it from the code
  or data, OR the request contradicts a recorded decision (an ADR), OR the premise is wrong / the
  intent is unclear. Hold for the human. Do NOT grill over small uncertainties you can reasonably
  decide — scope those and proceed.

REWRITE the title to be specific: "<area/surface>: <specific behavior or change>".

WRITE the body for your route (Markdown), starting with this exact line:
{disclaimer}

- ready -> an Agent Brief with these sections: **Summary**; **Verified** (re-derive the claim
  against named functions/branches on the real data — quote the numbers); **Current behavior**
  (grounded numbers); **Desired behavior**; **Key interfaces** (where the change lives — say
  "explore fresh; pointers, not line numbers", and name any traps); **Acceptance criteria** (a
  checkbox list; bake grounded numeric literals in where they apply, and include a test that
  would fail if the bug regressed); **Out of scope** (explicit don'ts).
- grill -> questions IN THE MAINTAINER'S VOICE: talk about the app's behavior and their real
  numbers, NEVER about code symbols, ADR numbers, or file paths. Lead with the symptom/impact,
  give 2-3 concrete options grounded in real examples, and say which you'd pick and why. Max 5.
- mockup -> a short `/ui-mockups` kickoff: the one surface in scope and 3-4 wildly-different
  concept axes.

DIALS (only for "ready"):
- complexity: "standard" (ordinary logic -> sonnet/Terra) or "deep" (correctness-sensitive,
  design-heavy -> opus/Sol). If this repo is correctness-sensitive (e.g. medical), lean deep.
- effort: "low" | "medium" | "high" | "extra" — how much work it warrants.

END your message with the decision as ONE valid JSON object. It may follow brief
reasoning, but the JSON must be the LAST thing in your message and must parse — escape
every newline inside a string value as \\n and every quote as \\":
{"route": "ready" | "grill" | "mockup",
 "title": "<rewritten title>",
 "complexity": "standard" | "deep",
 "effort": "low" | "medium" | "high" | "extra",
 "body": "<the Markdown to post, newlines written as \\n>"}
For "grill"/"mockup", omit complexity and effort."""


class Intake:
    """Runs a tool-agnostic grounding session and reads back its routing decision."""

    def __init__(self, runner: _WorktreeRunner):
        self.runner = runner

    def intake(self, repo: str, workdir: str, issue: dict, extra: str = "") -> IntakeResult:
        """Ground + route one issue. Uses a detached worktree at origin/main so any data
        pull is isolated from the main checkout — read-only, never a build. `extra` carries
        the maintainer's reply when resuming a held issue (ADR 0019)."""
        n = issue["number"]
        wt = Path(workdir) / ".agentflow" / "worktrees" / f"{self.runner.tool}-intake" / f"issue-{n}"
        try:
            self.runner.prepare_worktree_detached(workdir, "origin/main", wt)
            self.runner.provision(wt)
        except subprocess.CalledProcessError as e:
            return _held(f"intake worktree/provision failed: {e}")

        prompt = _fill(INTAKE_PROMPT, repo=repo, n=str(n), disclaimer=_DISCLAIMER,
                       title=issue.get("title", ""), body=issue.get("body") or "(no description)")
        if extra:
            prompt += ("\n\nTHE MAINTAINER HAS REPLIED to your earlier questions — treat this as the "
                       "answer: promote to ready if it's settled, else re-post only what's still open.\n"
                       f"---\n{extra}\n---")
        # Ground at the capable tier — a cheap model that mis-scopes is the expensive miss.
        ok, message = self.runner.launch(prompt, cwd=str(wt), model=self.runner.model_for(Complexity.DEEP))
        if not ok:
            return _held("intake session errored (launch non-zero)")
        return parse_intake(message)


def _ensure_label(repo: str, name: str) -> None:
    """Idempotently create the label so `--add-label` can't fail on a fresh repo."""
    color = _LABEL_COLORS.get(name, "ededed")
    _run(["gh", "label", "create", name, "--repo", repo, "--color", color, "--force"])


def apply_intake(repo: str, issue_number: int, current_title: str,
                 current_labels: list[str], result: IntakeResult) -> str:
    """Write the decision to GitHub: rewrite the title, post the brief/questions, set
    the one state label + dials (clearing any other state label). Impure; returns a
    one-line summary."""
    labels = intake_labels(result)
    comment = result.body
    if result.title and result.title != current_title:
        _run(["gh", "issue", "edit", str(issue_number), "--repo", repo, "--title", result.title])
        comment = f'> Retitled from: "{current_title}"\n\n{comment}'
    _run(["gh", "issue", "comment", str(issue_number), "--repo", repo, "--body", comment])

    for name in labels:
        _ensure_label(repo, name)
    args = ["gh", "issue", "edit", str(issue_number), "--repo", repo]
    for name in labels:
        args += ["--add-label", name]
    for name in STATE_LABELS:  # keep exactly one state label — clear stale holds on promote
        if name not in labels and name in current_labels:
            args += ["--remove-label", name]
    _run(args)
    tail = "" if result.parsed else " (fail-safe hold)"
    return f"routed -> {result.route.value}{tail}"
