"""Intake — the autonomous front of the pipe (ADR 0016).

Every open issue with no state label passes through here before it can be built, except
`wayfinder:*` planning artifacts, which stay upstream until wayfinder files build tickets.
Intake *grounds* the request (reads the code, and pulls a read-only real-data snapshot
if the repo declares one), *rewrites* it into something specific, and *routes* it to
exactly one outcome:

- `ready-for-agent` — clear as day; intake writes the build brief and stamps the two
  dials (complexity + effort, ADR 0018) so the loop can build it.
- `agentflow:needs-grilling` — a real, outcome-changing fork it can't settle from
  code/data, or a request that contradicts a recorded ADR; it posts questions in the
  *maintainer's* voice and holds (ADR 0019).
- `agentflow:needs-mockup` — a user-facing surface beyond a minor bugfix; holds for a
  `/ui-mockups` pass.

Same shape as the reviewer: a tool-agnostic session does the grounding and emits a
strict-JSON decision; `parse_intake` turns that into an `IntakeResult`. Parsing is
**fail-safe** — anything we can't read as a confident `ready`/`mockup` falls back to
holding for a human (`grill`), never an accidental build.

Deep module: `Intake(runner).intake(...) -> IntakeResult`, then `apply_intake(...)`
writes it to GitHub. `parse_intake` and `intake_labels` are pure — the test surface.
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from agentflow import live
from agentflow.runner import Complexity, Effort, _WorktreeRunner, _run, worktree_session

_FENCE_RE = re.compile(r"```[a-zA-Z]*\s*\n(.*?)\n```", re.DOTALL)
_DISCLAIMER = "> *agentflow intake — generated by AI.*"
INTAKE_MARK = "agentflow intake"  # substring that identifies an intake comment we posted

# Invisible fence (renders as nothing) marking where the brief ends and the preserved
# as-filed text begins. Lets a re-intake swap the brief in place instead of stacking a
# second one — everything from this marker down is the untouched original.
_ORIGINAL_MARK = "<!-- agentflow:original-below -->"

# The thread reply on a ready routing: a short, conversational note — not the brief
# itself. The brief is a build input and lives in the description now; this comment is
# the human-facing "here's what I did" and carries the intake marker so resume still
# keys off it.
_READY_COMMENT = (
    f"{_DISCLAIMER}\n\n"
    "Grounded and scoped this — the full Agent Brief is in the description now, so the "
    "build and review read straight from it. Your issue as filed is preserved under a "
    "collapsed block at the bottom. Take a look, and reply here if any of the scope is off."
)


class IntakeRoute(str, Enum):
    READY = "ready"     # build-ready — write the brief, stamp dials, proceed
    GRILL = "grill"     # hold: a real fork only the human can settle
    MOCKUP = "mockup"   # hold: needs a locked visual spec first
    NOTHING_NEW = "nothing-new"  # resume found nothing genuinely open changed — stay quiet


@dataclass(frozen=True, slots=True)
class IntakeResult:
    route: IntakeRoute
    body: str                        # the brief / questions / mockup kickoff to post
    title: str = ""                  # rewritten title ("" = leave as filed)
    complexity: Complexity | None = None
    effort: Effort | None = None
    parsed: bool = True
    detail: str = ""
    infra_failed: bool = False       # a worktree/provision/launch failure, not a model decision


def _held(detail: str) -> IntakeResult:
    """Fail-safe: an intake we can't read as confident-ready holds for the human."""
    body = (f"{_DISCLAIMER}\n\nI couldn't ground this into a confident scope on my own. "
            "Let's settle it together — reply here with what you meant, or run "
            "`/agentflow pickup` to drive it live.")
    return IntakeResult(IntakeRoute.GRILL, body, parsed=False, detail=detail)


def _infra_failed(detail: str) -> IntakeResult:
    """An *infrastructure* failure — the worktree, provision, or launch fell over before
    the model ever weighed in. Unlike a model-level hold this is not the issue's fault, so
    the loop retries it silently next cycle rather than spending the issue's state on a
    spammy hold (ADR 0019 — no spam). The body is only ever posted if the loop's bounded
    backstop fires after a run of consecutive failures."""
    body = (f"{_DISCLAIMER}\n\nI keep hitting a setup problem before I can even start "
            "grounding this — it's on my end, not your issue. I'll keep retrying; flagging "
            "it here in case it needs a look.")
    return IntakeResult(IntakeRoute.GRILL, body, parsed=False, detail=detail, infra_failed=True)


def _json_objects(text: str) -> list[dict]:
    """Candidate JSON dicts from a model message, best-guess first: any fenced ```json
    blocks (last first), the whole message, then every balanced {...} object scanning
    from the end. Robust to a decision that follows the model's reasoning prose — models
    reason before they answer, so 'STRICT JSON only' is not reliable on its own."""
    text = text.strip()
    out: list[dict] = []

    def _try(s: str) -> None:
        try:
            obj = json.loads(s)
        except ValueError:
            return
        if isinstance(obj, dict):
            out.append(obj)

    for b in reversed(_FENCE_RE.findall(text)):
        _try(b.strip())
    _try(text)
    dec = json.JSONDecoder()
    for i in reversed([j for j, c in enumerate(text) if c == "{"]):
        try:
            obj, _end = dec.raw_decode(text[i:])
        except ValueError:
            continue
        if isinstance(obj, dict):
            out.append(obj)
    return out


def _enum_or_none(enum, raw):
    try:
        return enum(str(raw).strip().lower())
    except ValueError:
        return None


def parse_intake(payload: str) -> IntakeResult:
    """Parse a grounding session's JSON decision. Pure, fail-safe (test surface).

    Recovers the decision even when the model prefixes it with reasoning prose. A
    confident `ready` needs a valid route and a non-empty body; a missing/garbled
    complexity defaults to `deep` (a bigger model is the safe sizing miss, never a wrong
    build) and effort to `medium`. Anything unreadable → held for a human. Never raises.
    """
    try:
        for data in _json_objects(payload):
            route = _enum_or_none(IntakeRoute, data.get("route"))
            if route is None:
                continue  # not the decision object — try the next candidate
            if route is IntakeRoute.NOTHING_NEW:
                return IntakeResult(route, "")  # a no-op resume: no body, nothing to post
            body = str(data.get("body", "")).strip()
            if not body:
                return _held("intake decision carried no body")
            title = str(data.get("title", "")).strip()
            if route is IntakeRoute.READY:
                complexity = _enum_or_none(Complexity, data.get("complexity")) or Complexity.DEEP
                effort = _enum_or_none(Effort, data.get("effort")) or Effort.MEDIUM
                return IntakeResult(route, body, title, complexity, effort)
            return IntakeResult(route, body, title)
        return _held("no JSON decision with a valid route in the intake output")
    except Exception as e:  # noqa: BLE001 — fail-safe, never propagate
        return _held(f"parse error: {type(e).__name__}")


def compose_ready_body(brief: str, current_body: str) -> str:
    """The issue body after a ready routing: the Agent Brief on top, the as-filed text
    preserved verbatim under a collapsed `<details>` at the bottom (ADR 0016/0022 — the
    brief must live where builder and reviewer read it). Pure (test surface).

    Idempotent on re-intake: if `current_body` already carries a composed brief (the
    `_ORIGINAL_MARK` fence), the previously-preserved original is kept exactly as-is and
    only the brief above it is replaced — never a second `<details>`, never the old brief
    nested inside the new one."""
    brief = brief.strip()
    idx = current_body.find(_ORIGINAL_MARK)
    if idx != -1:
        return f"{brief}\n\n{current_body[idx:].strip()}"
    original = current_body.strip() or "_(no description as filed)_"
    return (f"{brief}\n\n{_ORIGINAL_MARK}\n<details>\n<summary>Original issue as filed</summary>"
            f"\n\n{original}\n\n</details>")


def intake_labels(result: IntakeResult) -> list[str]:
    """The labels to stamp for a routed issue — exactly one state, plus dials when
    ready. Pure (test surface)."""
    if result.route is IntakeRoute.READY:
        return ["ready-for-agent",
                f"agentflow:complexity:{result.complexity.value}",
                f"agentflow:effort:{result.effort.value}"]
    if result.route is IntakeRoute.MOCKUP:
        return ["agentflow:needs-mockup"]
    return ["agentflow:needs-grilling"]


_DOUBLE_QUOTED_RE = re.compile(r"^>\s*>", re.MULTILINE)


def _strip_quoted_lines(body: str) -> str:
    """Remove re-quoted lines (starting with '> >') so a GitHub quote-reply of our
    comment doesn't mask our marker. Our marker lives on a single-'>' line in our
    posts — those are kept so we can still detect our own comments."""
    return "\n".join(
        line for line in body.splitlines() if not _DOUBLE_QUOTED_RE.match(line)
    )


def awaiting_recheck(comments: list[dict], allowlist: set[str] | None = None) -> bool:
    """True when a held issue's most recent non-empty comment from an allowlisted author
    is the maintainer's reply — i.e. they answered and it's our move again (ADR 0019).
    False when the last word is ours, or there are no qualifying comments. Pure.

    Quote-reply lines (starting with '>') are stripped before scanning so a maintainer
    who quotes our comment still counts as a reply, not as us. Comments from authors not
    in *allowlist* are skipped entirely; *allowlist=None* disables the author filter."""
    for c in reversed(comments):
        body = c.get("body", "").strip()
        if not body:
            continue
        if allowlist is not None and c.get("author", {}).get("login", "") not in allowlist:
            continue
        return INTAKE_MARK not in _strip_quoted_lines(body)
    return False


def replies_since_intake(comments: list[dict], allowlist: set[str] | None = None) -> str:
    """The maintainer's comment(s) after our last intake comment — their answer text.
    Pure (test surface).

    Quote-reply lines are stripped before scanning for the cut point so a maintainer
    quote-reply is not mistaken for our marker. Only comments from *allowlist* authors
    are collected; *allowlist=None* collects all (backwards-compatible)."""
    tail = []
    for c in reversed(comments):
        if INTAKE_MARK in _strip_quoted_lines(c.get("body", "")):
            break
        if allowlist is not None and c.get("author", {}).get("login", "") not in allowlist:
            continue
        tail.append(c.get("body", "").strip())
    return "\n\n".join(b for b in reversed(tail) if b)


# The three state labels intake owns — kept mutually exclusive on an issue.
STATE_LABELS = ("ready-for-agent", "agentflow:needs-grilling", "agentflow:needs-mockup")

# Dial label prefixes — cleared when stamping new dials (or dropping to a hold route).
_DIAL_PREFIXES = ("agentflow:complexity:", "agentflow:effort:")

# Bare pre-enrollment vocabulary → agentflow:* canonical form.
# Note: ready-for-agent stays bare (ADR 0018 — settled; excluded from this map).
_LEGACY_LABEL_MAP: dict[str, str] = {
    "needs-grilling": "agentflow:needs-grilling",
    "needs-mockup": "agentflow:needs-mockup",
}

_LABEL_COLORS = {
    "ready-for-agent": "0e8a16",
    "agentflow:needs-grilling": "d93f0b",
    "agentflow:needs-mockup": "f9d0c4",
    "agentflow:complexity:standard": "1d76db",
    "agentflow:complexity:deep": "0052cc",
    "agentflow:effort:low": "c5def5",
    "agentflow:effort:medium": "5319e7",
    "agentflow:effort:high": "b60205",
    "agentflow:effort:extra": "006b75",
}


def _fill(template: str, **kw: str) -> str:
    """Substitute {name} placeholders without str.format — brace-safe against issue
    bodies that contain literal `{`/`}` (code snippets, JSON)."""
    out = template
    for k, v in kw.items():
        out = out.replace("{" + k + "}", str(v))
    return out


INTAKE_PROMPT = """You are agentflow's intake for {repo} issue #{n}. You turn one freshly-filed,
often-vague issue into a single decision. You are unattended — nobody is here to answer — so
you act on your best judgment, never by asking, EXCEPT where a genuine fork needs the human.

YOUR ONLY OUTPUT IS THE JSON DECISION described at the end. Do NOT write to GitHub yourself:
do not edit the issue title, do not post or edit comments, do not add or remove labels. The
harness reads your JSON and applies all of that for you — if you also do it, the issue gets a
duplicate title change and a duplicate comment. The "rewrite the title" and "write the body"
steps below mean *put those values in the JSON*, not run `gh`. The only commands you run are
READ-ONLY grounding (reading code, the read-only data pull).

The issue as filed:
Title: {title}
---
{body}
---

GROUND IT FIRST — do the work, don't guess:
- Read the code in this checkout deeply enough to know where the change would live and whether
  the premise even holds. Cite what you found.
- If this repo's AGENTS.md / CLAUDE.md declares a read-only real-data pull (e.g. ciq's
  `ciq-pull-db` -> a readonly snapshot), RUN IT and check the real numbers. Read-only only:
  never touch live/authoritative data, never write code here.
- Verify the claim. If it's already implemented, or the premise doesn't hold (e.g. the numbers
  moved), say so with the evidence — that is a hold, not a build.

THEN CHOOSE ONE ROUTE:
- "ready" — clear as day after grounding: you know exactly what to build and nothing material is
  left to decide. Only route here when a confident, well-scoped build is possible.
- "mockup" — it needs a user-facing surface beyond a minor bugfix; the visual/interaction design
  must be locked first.
- "grill" — a real choice remains that CHANGES THE RESULT and you can't settle it from the code
  or data, OR the request contradicts a recorded decision (an ADR), OR the premise is wrong / the
  intent is unclear. Hold for the human. Do NOT grill over small uncertainties you can reasonably
  decide — scope those and proceed.

REWRITE the title to be specific: "<area/surface>: <specific behavior or change>".

WRITE the body for your route (Markdown), starting with this exact line:
{disclaimer}

- ready -> an Agent Brief with these sections: **Summary**; **Verified** (re-derive the claim
  against named functions/branches on the real data — quote the numbers); **Current behavior**
  (grounded numbers); **Desired behavior**; **Key interfaces** (where the change lives — say
  "explore fresh; pointers, not line numbers", and name any traps); **Acceptance criteria** (a
  checkbox list; bake grounded numeric literals in where they apply, and include a test that
  would fail if the bug regressed); **Out of scope** (explicit don'ts).
- grill -> questions IN THE MAINTAINER'S VOICE: talk about the app's behavior and their real
  numbers, NEVER about code symbols, ADR numbers, or file paths. Lead with the symptom/impact,
  give 2-3 concrete options grounded in real examples, and say which you'd pick and why. Max 5.
- mockup -> a short `/ui-mockups` kickoff: the one surface in scope and 3-4 wildly-different
  concept axes.

DIALS (only for "ready"):
- complexity: "standard" (ordinary logic -> sonnet/Terra) or "deep" (correctness-sensitive,
  design-heavy -> opus/Sol). If this repo is correctness-sensitive (e.g. medical), lean deep.
- effort: "low" | "medium" | "high" | "extra" — how much work it warrants.

END your message with the decision as ONE valid JSON object. It may follow brief
reasoning, but the JSON must be the LAST thing in your message and must parse — escape
every newline inside a string value as \\n and every quote as \\":
{"route": "ready" | "grill" | "mockup",
 "title": "<rewritten title>",
 "complexity": "standard" | "deep",
 "effort": "low" | "medium" | "high" | "extra",
 "body": "<the Markdown to post, newlines written as \\n>"}
For "grill"/"mockup", omit complexity and effort."""


def intake_prompt(repo: str, issue: dict, extra: str = "") -> str:
    """The durable provider input for one Intake stage."""
    prompt = _fill(INTAKE_PROMPT, repo=repo, n=str(issue["number"]), disclaimer=_DISCLAIMER,
                   title=issue.get("title", ""), body=issue.get("body") or "(no description)")
    if extra:
        prompt += ("\n\nTHE MAINTAINER HAS REPLIED to your earlier hold — treat this as their "
                   "answer or waiver: promote to ready if the issue is now settled (they answered "
                   "your questions, waived the visual spec requirement, or pointed at a locked spec), "
                   "else re-post ONLY what's still open. "
                   "IF this issue was held for a MOCKUP and a variant round was already drawn (a "
                   "comment on the issue naming variants A/B/C/D with screenshots), the reply may be "
                   "a PICK — \"B\", \"the second one\", \"A but tighter\". In that case: read that "
                   "mockup comment (it links the committed variant files on a mockup branch), map "
                   "the pick to its variant, and route \"ready\" with a brief that references THAT "
                   "chosen variant's committed file as the LOCKED visual spec the build must match "
                   "(ADR 0018 — the build's screenshot is checked against the locked mockup, so name "
                   "the exact file/branch). A request for a DIFFERENT or fresh set is NOT a pick — "
                   "re-hold (route \"mockup\") as a follow-up; never auto-loop a new variant round. "
                   'If nothing genuinely open changed — the reply was chit-chat, or it didn\'t move '
                   'any open question — answer route "nothing-new" (no body) and I\'ll stay quiet '
                   "rather than restate myself.\n"
                   f"---\n{extra}\n---")
    return prompt


class Intake:
    """Runs a tool-agnostic grounding session and reads back its routing decision."""

    def __init__(self, runner: _WorktreeRunner):
        self.runner = runner

    def intake(self, repo: str, workdir: str, issue: dict, extra: str = "") -> IntakeResult:
        """Ground + route one issue. Uses a detached worktree at origin/main so any data
        pull is isolated from the main checkout — read-only, never a build. `extra` carries
        the maintainer's reply when resuming a held issue (ADR 0019)."""
        n = issue["number"]
        wt = Path(workdir) / ".agentflow" / "worktrees" / f"{self.runner.tool}-intake" / f"issue-{n}"
        try:
            self.runner.prepare_worktree_detached(workdir, "origin/main", wt)
            self.runner.provision(wt)
        except subprocess.CalledProcessError as e:
            return _infra_failed(f"intake worktree/provision failed: {e}")

        prompt = intake_prompt(repo, issue, extra)
        # Ground at the capable tier — a cheap model that mis-scopes is the expensive miss.
        model = self.runner.model_for(Complexity.DEEP)
        session = live.Session(repo=repo, number=n, title=issue.get("title", ""),
                               stage="triaging", tool=self.runner.tool, model=model, branch=None)
        with worktree_session(wt, session):
            ok, message = self.runner.launch(prompt, cwd=str(wt), model=model)
        if not ok:
            return _infra_failed("intake session errored (launch non-zero)")
        return parse_intake(message)


def _ensure_label(repo: str, name: str) -> None:
    """Idempotently create the label so `--add-label` can't fail on a fresh repo."""
    color = _LABEL_COLORS.get(name, "ededed")
    _run(["gh", "label", "create", name, "--repo", repo, "--color", color, "--force"])


def _issue_body(repo: str, issue_number: int) -> str:
    """The issue's current body text, or "" if it can't be read. Impure."""
    r = _run(["gh", "issue", "view", str(issue_number), "--repo", repo, "--json", "body"])
    if r.returncode != 0:
        return ""
    try:
        return json.loads(r.stdout or "{}").get("body") or ""
    except ValueError:
        return ""


def _latest_comment(repo: str, issue_number: int) -> str:
    """The issue's most recent non-empty comment body, or "" if none / unreadable. Impure."""
    r = _run(["gh", "issue", "view", str(issue_number), "--repo", repo, "--json", "comments"])
    if r.returncode != 0:
        return ""
    try:
        comments = json.loads(r.stdout or "{}").get("comments", [])
    except ValueError:
        return ""
    for c in reversed(comments):
        if c.get("body", "").strip():
            return c["body"].strip()
    return ""


def apply_intake(repo: str, issue_number: int, current_title: str,
                 current_labels: list[str], result: IntakeResult) -> str:
    """Write the decision to GitHub, then set the one state label + dials (clearing any
    other state label). Impure; returns a one-line summary.

    On `ready` the brief is a **build input**: it goes into the issue *body* (where the
    builder prompt and reviewer acceptance read it, ADR 0016/0022), the as-filed text is
    preserved below it, and the thread gets a short conversational note. On `grill` /
    `mockup` — those are conversations, not build inputs — the full text stays a comment.

    No-spam (ADR 0019): a `nothing-new` resume writes nothing at all, and an apply whose
    comment materially matches the latest comment we already posted is skipped — a
    nothing-changed recheck must not restate itself."""
    if result.route is IntakeRoute.NOTHING_NEW:
        return "nothing new — nothing to post"

    labels = intake_labels(result)
    retitled_from = current_title if (result.title and result.title != current_title) else None
    comment = _READY_COMMENT if result.route is IntakeRoute.READY else result.body
    if retitled_from is not None:
        comment = f'> Retitled from: "{retitled_from}"\n\n{comment}'

    # Idempotent: if our last word on this issue already says the same thing, changing
    # nothing (no comment, no label churn) is the whole point — don't re-post it.
    exact_labels = set(labels).issubset(current_labels)
    stale_state = any(name in current_labels and name not in set(labels) for name in STATE_LABELS)
    stale_dials = any(any(name.startswith(p) for p in _DIAL_PREFIXES)
                      and name not in set(labels) for name in current_labels)
    title_done = not retitled_from
    if (INTAKE_MARK in comment and comment.strip() == _latest_comment(repo, issue_number)
            and exact_labels and not stale_state and not stale_dials and title_done):
        return f"unchanged -> {result.route.value} (already posted)"

    if retitled_from is not None:
        _run(["gh", "issue", "edit", str(issue_number), "--repo", repo, "--title", result.title])
    if result.route is IntakeRoute.READY:
        body = compose_ready_body(result.body, _issue_body(repo, issue_number))
        _run(["gh", "issue", "edit", str(issue_number), "--repo", repo, "--body", body])
    _run(["gh", "issue", "comment", str(issue_number), "--repo", repo, "--body", comment])

    for name in labels:
        _ensure_label(repo, name)
    new_labels_set = set(labels)
    args = ["gh", "issue", "edit", str(issue_number), "--repo", repo]
    for name in labels:
        args += ["--add-label", name]
    for name in STATE_LABELS:  # keep exactly one state label — clear stale holds on promote
        if name not in new_labels_set and name in current_labels:
            args += ["--remove-label", name]
    for name in current_labels:  # clear stale dials — a re-route leaves exactly one of each
        if any(name.startswith(p) for p in _DIAL_PREFIXES) and name not in new_labels_set:
            args += ["--remove-label", name]
    _run(args)
    tail = "" if result.parsed else " (fail-safe hold)"
    return f"routed -> {result.route.value}{tail}"


def intake_result_is_durable(repo: str, issue_number: int, result: IntakeResult) -> bool:
    """Verify that the routing decision is visible on GitHub before disposal."""
    if result.route is IntakeRoute.NOTHING_NEW:
        return True
    r = _run(["gh", "issue", "view", str(issue_number), "--repo", repo,
              "--json", "body,labels,comments"])
    if r.returncode != 0:
        return False
    try:
        issue = json.loads(r.stdout or "{}")
    except json.JSONDecodeError:
        return False
    labels = {label.get("name") for label in issue.get("labels", [])
              if isinstance(label, dict)}
    if not set(intake_labels(result)).issubset(labels):
        return False
    comments = [comment.get("body", "") for comment in issue.get("comments", [])
                if isinstance(comment, dict)]
    if result.route is IntakeRoute.READY:
        return result.body in (issue.get("body") or "") and any(INTAKE_MARK in c for c in comments)
    return any(result.body in comment for comment in comments)


def sweep_legacy_labels(repo: str) -> list[str]:
    """Migrate bare pre-enrollment needs-* labels to the agentflow:* vocabulary on open
    issues. Idempotent — safe to run more than once. Returns one-line change descriptions,
    one per issue touched."""
    r = _run(["gh", "issue", "list", "--repo", repo, "--state", "open",
              "--json", "number,labels", "--limit", "500"])
    if r.returncode != 0:
        return [f"error: could not list issues (exit {r.returncode})"]
    changed = []
    for issue in json.loads(r.stdout or "[]"):
        n = issue["number"]
        names = {lbl["name"] for lbl in issue.get("labels", [])}
        to_add: list[str] = []
        to_remove: list[str] = []
        for bare, namespaced in _LEGACY_LABEL_MAP.items():
            if bare in names:
                if namespaced not in names:
                    to_add.append(namespaced)
                to_remove.append(bare)
        if not to_remove:
            continue
        args = ["gh", "issue", "edit", str(n), "--repo", repo]
        for name in to_add:
            _ensure_label(repo, name)
            args += ["--add-label", name]
        for name in to_remove:
            args += ["--remove-label", name]
        _run(args)
        parts = []
        if to_add:
            parts.append(f"added {', '.join(sorted(to_add))}")
        parts.append(f"removed {', '.join(sorted(to_remove))}")
        changed.append(f"#{n}: {'; '.join(parts)}")
    return changed
